// The card-art choice page (prime-game-ui#3): the four drawing styles of the how-to cards, each shown as the game
// draws its two cards (ToyPanelHowto with 4 ToyHowtoFrame frames, the last ToyHowtoFrameDone, the art 160 x 120 above
// each caption from the copy deck, scaled to the phone) and then its 8 panels larger. The whole style block is the
// button that picks it; a note says what to change or mix. styles.json holds the Ukrainian page texts and the cards;
// the art is pages/card-art/art/<style>/*.svg (own work, LICENCES.json), checked by art-contract.js on every run.
//
//   node pages/card-art/build.js          check the art, write card-ui.css and card-art.html
//   node pages/card-art/build.js --check  exit 1 when the art breaks its contract or either file is stale
//
// card-ui.css (lint profile "generated", tools/lint/targets.json) holds the components CSS of the variations the cards
// use, emitted from the tokens by pages/components/emit-css.js. The art is scenery inlined as SVG (ids rewritten per
// copy, so the 64 copies never clash); page.css is the chrome, outside the lint like the other pages' page.css.
// The choice is saved through the artifact runtime's db capability (declare {db: {}, user: {}} when publishing):
// collection "cards3", document "choice", { style, note, at } (card-art.js). Deterministic and LF-only. Node 20, no
// packages.
'use strict';

const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const ROOT = path.resolve(HERE, '..', '..');
const api = require(path.join(ROOT, 'tools', 'tokens', 'api.js'));
const { emitComponentsCss } = require(path.join(ROOT, 'pages', 'components', 'emit-css.js'));
const { readDeck } = require(path.join(ROOT, 'tools', 'copy', 'deck.js'));
const { checkArt, PANELS, ART } = require('./art-contract.js');

const OUT_UI = 'pages/card-art/card-ui.css';
const OUT_HTML = 'pages/card-art/card-art.html';
const FONT_LINK = 'https://fonts.googleapis.com/css2?family=Comfortaa:wght@400;600;700&display=swap';
const HEADER_UI = '/* Generated by pages/card-art/build.js from tools/tokens/api.js (pages/components/emit-css.js): the variations the how-to cards use. Do not edit. */';
const USED = ['ToyPanelHowto', 'ToyColumnSixteen', 'ToyRowSixteen', 'ToyTitleOnLight', 'ToyHowtoNote', 'ToyRowTwelve',
  'ToyHowtoFrame', 'ToyHowtoFrameDone', 'ToyColumnEight', 'ToyHowtoCaption'];
const ROOT_TAG = '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="240" viewBox="0 0 320 240">';
const MAX_PAGE = 2 * 1024 * 1024;

class BuildError extends Error {}
const fail = (msg) => { throw new BuildError(msg); };
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const readText = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8').replace(/\r\n/g, '\n');
const isStr = (v) => typeof v === 'string' && v.trim() !== '' && v === v.trim();

function loadData() {
  let data;
  try { data = JSON.parse(readText('pages/card-art/styles.json')); } catch (e) { fail(`styles.json: ${e.message}`); }
  for (const k of ['title', 'eyebrow', 'heading', 'lead', 'source', 'source_link', 'report_url', 'issue_url', 'collection', 'doc', 'recommended', 'why', 'note_key']) {
    if (!isStr(data[k])) fail(`styles.json: "${k}" is a non-empty string`);
  }
  if (!/^[a-z][a-z0-9_]*$/.test(data.collection) || !/^[a-z][a-z0-9_]*$/.test(data.doc)) fail('styles.json: "collection" and "doc" are single db path segments');
  if (!Array.isArray(data.styles) || data.styles.length < 2) fail('styles.json: "styles" lists two or more styles');
  const ids = new Set();
  data.styles.forEach((s, i) => {
    if (!/^[a-z][a-z-]*$/.test(s.id || '') || ids.has(s.id)) fail(`styles.json: styles[${i}].id is a unique folder name`);
    ids.add(s.id);
    for (const k of ['name_uk', 'name_en', 'one_line_uk']) if (!isStr(s[k])) fail(`styles.json: styles[${i}] (${s.id}): "${k}" is a non-empty string`);
  });
  if (!ids.has(data.recommended)) fail(`styles.json: "recommended" ${data.recommended} is not one of the styles`);
  if (!Array.isArray(data.cards) || data.cards.length !== 2) fail('styles.json: "cards" holds the two cards');
  const seen = [];
  data.cards.forEach((c, i) => {
    if (!isStr(c.id) || !isStr(c.title_key) || !Array.isArray(c.frames) || c.frames.length !== 4) fail(`styles.json: cards[${i}] has id, title_key and 4 frames`);
    c.frames.forEach((f, j) => {
      if (!PANELS.includes(f.panel) || !isStr(f.key)) fail(`styles.json: cards[${i}].frames[${j}] names a panel and a copy key`);
      seen.push(f.panel);
    });
  });
  if (seen.slice().sort().join() !== PANELS.slice().sort().join()) fail('styles.json: the two cards show the 8 panels once each');
  return data;
}

function loadCopy(data) {
  const { entries, errors } = readDeck(readText('copy/strings.csv'));
  if (errors.length) fail(`copy/strings.csv: ${errors[0]}`);
  const byKey = new Map(entries.map((e) => [e.key, e]));
  const t = (key) => {
    const e = byKey.get(key);
    if (!e || !isStr(e.uk && e.uk[0]) || !isStr(e.en && e.en[0])) fail(`copy/strings.csv: no uk and en text for ${key}`);
    return { uk: e.uk[0], en: e.en[0] };
  };
  const keys = [data.note_key];
  for (const c of data.cards) { keys.push(c.title_key); for (const f of c.frames) keys.push(f.key); }
  return Object.fromEntries(keys.map((k) => [k, t(k)]));
}

// One panel's SVG for inlining: no licence comment, no fixed size, every id prefixed so copies never clash.
function inlineSvg(style, panel, pre, attrs) {
  const text = fs.readFileSync(path.join(ART, style, `${panel}.svg`), 'utf8').replace(/\r\n/g, '\n');
  const lines = text.split('\n');
  if (lines[1] !== ROOT_TAG) fail(`${style}/${panel}.svg: line 2 is not the contract's root tag`);
  const body = lines.slice(2).join('\n').replace(/\s+$/, '');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 240" ${attrs}>\n`
    + body.replace(/(\bid="|\bhref="#|url\(#)([ds][1-4]-)/g, `$1${pre}$2`);
}

const both = (t) => `<span class="l-uk">${esc(t.uk)}</span><span class="l-en" lang="en">${esc(t.en)}</span>`;

function frame(f, i, n, copy, svg) {
  const cls = i === n - 1 ? 'tv-ToyHowtoFrameDone' : 'tv-ToyHowtoFrame';
  return `<span class="${cls}"><span class="tv-ToyColumnEight">${svg}\n<span class="tv-ToyHowtoCaption">${both(copy[f.key])}</span></span></span>`;
}

function styleBlock(data, s, n, copy) {
  const short = s.id.split('-').map((w) => w[0]).join('');
  const rec = s.id === data.recommended;
  const card = (c) => `<span class="card-fit"><span class="card tv-ToyPanelHowto"><span class="tv-ToyColumnSixteen">`
    + `<span class="tv-ToyRowSixteen"><span class="tv-ToyTitleOnLight">${both(copy[c.title_key])}</span><span class="tv-ToyHowtoNote">${both(copy[data.note_key])}</span></span>`
    + `<span class="tv-ToyRowTwelve">${c.frames.map((f, i) => frame(f, i, c.frames.length, copy, inlineSvg(s.id, f.panel, `${short}c-`, 'class="art" aria-hidden="true" focusable="false"'))).join('\n')}</span>`
    + '</span></span></span>';
  const big = data.cards.flatMap((c) => c.frames.map((f, i) => frame(f, i, c.frames.length, copy,
    inlineSvg(s.id, f.panel, `${short}b-`, `class="art" role="img" aria-label="${esc(copy[f.key].uk)}" focusable="false"`))));
  return [
    `<button type="button" class="style" data-style="${s.id}" id="style-${s.id}" aria-pressed="false" aria-labelledby="${s.id}-name" aria-describedby="${s.id}-line">`,
    `<span class="style-head"><span class="num" aria-hidden="true">${n}</span><span class="name" id="${s.id}-name">${esc(s.name_uk)}</span>`
      + `<span class="name-en" lang="en">${esc(s.name_en)}</span>${rec ? '<span class="badge">рекомендую</span>' : ''}</span>`,
    `<span class="line" id="${s.id}-line">${esc(s.one_line_uk)}</span>`,
    rec ? `<span class="why"><b>Чому рекомендую:</b> ${esc(data.why)}</span>` : null,
    '<span class="sub">Так картки виглядатимуть у грі</span>',
    `<span class="cards">${data.cards.map(card).join('\n')}</span>`,
    '<span class="sub">Кадри більшими</span>',
    `<span class="big">${big.join('\n')}</span>`,
    '<span class="pick-state" data-pick-state>Обрати цей стиль</span>',
    '</button>',
  ].filter((x) => x !== null).join('\n');
}

function build() {
  const data = loadData();
  const art = checkArt(data.styles.map((s) => s.id));
  if (art.problems.length) fail(`the art breaks its contract (node pages/card-art/art-contract.js):\n  ${art.problems.slice(0, 20).join('\n  ')}`);
  const copy = loadCopy(data);
  const sys = api.load({ root: ROOT });

  const emitted = emitComponentsCss(sys).replace(/\r\n/g, '\n');
  const blocks = new Map();
  let cur = null;
  for (const l of emitted.split('\n')) {
    const h = /^\/\* (Toy[A-Za-z]+): /.exec(l);
    if (h) { cur = []; blocks.set(h[1], cur); }
    if (cur) cur.push(l);
  }
  const uiParts = [HEADER_UI];
  for (const name of USED) {
    const b = blocks.get(name);
    if (!b) fail(`emit-css: no variation ${name}`);
    while (b.length && !b[b.length - 1].trim()) b.pop();
    uiParts.push(b.join('\n'));
  }
  const uiCss = uiParts.join('\n') + '\n';

  const style = (id, text) => `<style id="${id}">\n${text.replace(/\s+$/, '')}\n</style>`;
  const cfg = JSON.stringify({ collection: data.collection, doc: data.doc, names: Object.fromEntries(data.styles.map((s) => [s.id, s.name_uk])) }).replace(/</g, '\\u003c');
  const html = [
    '<!doctype html>',
    '<html lang="uk" data-lang="uk" data-text-size="default">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${esc(data.title)}</title>`,
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    `<link rel="stylesheet" href="${FONT_LINK}">`,
    style('toy-tokens', readText('dist/css/toy-tokens.css')),
    style('ca-ui', uiCss),
    style('ca-page', readText('pages/card-art/page.css')),
    '</head>',
    '<body>',
    '<!-- Generated by pages/card-art/build.js from styles.json, copy/strings.csv and pages/card-art/art. Do not edit. -->',
    '<main class="wrap">',
    '<header class="head">',
    `<span class="eyebrow"><a href="${esc(data.issue_url)}">${esc(data.eyebrow)}</a></span>`,
    `<h1>${esc(data.heading)}</h1>`,
    `<p class="lead">${esc(data.lead)}</p>`,
    `<p class="source">${esc(data.source)} <a href="${esc(data.report_url)}">${esc(data.source_link)}</a>.</p>`,
    '</header>',
    '<div class="bar">',
    '<span class="picked" id="ca-picked" aria-live="polite">Ще не обрано</span>',
    '<span class="seg" role="group" aria-label="мова підписів">Підписи<span class="seg-btns"><button type="button" data-lang-set="uk" aria-pressed="true">UA</button><button type="button" data-lang-set="en" aria-pressed="false">EN</button></span></span>',
    '</div>',
    '<p class="db" id="ca-db" role="status" data-state="wait">Підключаю збереження…</p>',
    '<div class="styles">',
    data.styles.map((s, i) => styleBlock(data, s, i + 1, copy)).join('\n'),
    '</div>',
    '<section class="note" aria-labelledby="ca-note-label">',
    '<label id="ca-note-label" for="ca-note">Що змінити або змішати?</label>',
    '<textarea id="ca-note" maxlength="2000" placeholder="Необов\'язково: наприклад, «пози з Комікс-гегу, але пластилінові форми»"></textarea>',
    '<button class="btn" type="button" id="ca-save">Зберегти нотатку</button>',
    '<p class="saved" id="ca-saved" aria-live="polite">Ще нічого не збережено</p>',
    '</section>',
    `<p class="foot">Картки зібрано з токенів ${esc(sys.version)}: ToyPanelHowto з чотирма ToyHowtoFrame (останній — ToyHowtoFrameDone), малюнок 160×120 над підписом, у масштабі під ширину екрана. `
      + 'Підписи — з колоди copy/strings.csv (task.*, howto.*), у грі вони під кадром, на малюнках тексту немає. '
      + 'Усі малюнки — власна робота агентів (own work), записана в LICENCES.json кожного стилю; кожен SVG перевірено на контракт брифу (pages/card-art/brief.md, розділ 1).</p>',
    '</main>',
    `<script id="ca-data" type="application/json">${cfg}</script>`,
    `<script>\n${readText('pages/card-art/card-art.js').replace(/\s+$/, '')}\n</script>`,
    '</body>',
    '</html>',
    '',
  ].join('\n');
  if (Buffer.byteLength(html) > MAX_PAGE) fail(`card-art.html is ${Math.round(Buffer.byteLength(html) / 1024)} KB, over 2 MB`);
  return { outputs: [[OUT_UI, uiCss], [OUT_HTML, html]], art };
}

function main(argv) {
  const check = argv.includes('--check');
  const unknown = argv.filter((a) => a !== '--check');
  if (unknown.length) {
    console.error(`unknown argument ${unknown[0]}\nusage: node pages/card-art/build.js [--check]`);
    return 2;
  }
  let res;
  try {
    res = build();
  } catch (e) {
    if (e instanceof BuildError || /^emit-css:|^tokens:/.test(e.message)) { console.error(`error: ${e.message}`); return 1; }
    throw e;
  }
  const { outputs, art } = res;
  for (const [file, text] of outputs) if (/\r/.test(text)) { console.error(`error: ${file} would contain CR bytes`); return 1; }
  console.log(`art contract: ${art.panels} panels in ${art.styles.length} styles OK`);
  if (check) {
    const stale = [];
    for (const [file, text] of outputs) {
      let disk = null;
      try { disk = fs.readFileSync(path.join(ROOT, file), 'utf8'); } catch (e) { disk = null; }
      if (disk !== text) stale.push(`${file} (${disk === null ? 'missing' : 'differs'})`);
    }
    if (stale.length) {
      console.log(`stale: ${stale.join(', ')}; run node pages/card-art/build.js`);
      return 1;
    }
    console.log(`up to date: ${outputs.map(([f]) => f).join(', ')}`);
    return 0;
  }
  for (const [file, text] of outputs) fs.writeFileSync(path.join(ROOT, file), text);
  const kb = (t) => `${Math.round(Buffer.byteLength(t) / 1024)} KB`;
  console.log(`wrote ${outputs.map(([f, t]) => `${f} (${kb(t)})`).join(', ')}`);
  return 0;
}

module.exports = { main };

if (require.main === module) process.exitCode = main(process.argv.slice(2));
