// The copy review page, round 2 (prime-game-ui#4): the open questions of copy/flags.json first, each with its options
// a-c as taps («Беру цей») and «Інакше» with an own text and a note, saved through the artifact runtime's db capability
// (collection "copy", one document per question id: {answer: option id | "other", text, note, at}); then what was
// decided after round 1 and every string of copy/strings.csv per wireframe screen, both folded and read-only.
//
//   node pages/copy/build.js          write copy-ui.css and copy.html
//   node pages/copy/build.js --check  fail when either is stale
//
// copy-ui.css (lint profile "generated", tools/lint/targets.json) holds the components CSS of the variations the page
// uses, emitted from the tokens by pages/components/emit-css.js. page.css is the page's chrome (layout only, like
// pages/components/page.css), outside the lint. Node 20, no packages.
'use strict';

const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const ROOT = path.resolve(HERE, '..', '..');
const api = require(path.join(ROOT, 'tools', 'tokens', 'api.js'));
const { emitComponentsCss } = require(path.join(ROOT, 'pages', 'components', 'emit-css.js'));
const D = require(path.join(ROOT, 'tools', 'copy', 'deck.js'));

const OUT_UI = 'pages/copy/copy-ui.css';
const OUT_HTML = 'pages/copy/copy.html';
const FONT_LINK = 'https://fonts.googleapis.com/css2?family=Comfortaa:wght@300..700&display=swap';
const HEADER_UI = '/* Generated by pages/copy/build.js from tools/tokens/api.js (pages/components/emit-css.js): the variations the copy page uses. Do not edit. */';
const USED = ['ToyPanelMenu', 'ToyChipNew', 'ToyChipNewText', 'ToyButtonPrimary',
  'ToyButtonSecondary', 'ToyButtonGhostOnLight', 'ToyField', 'ToyTextOnLight', 'ToyTextMutedOnLight', 'ToyTitleOnLight'];

// Where a key lives: the longest matching prefix names its wireframe screen; the rest are shared.
const SCREEN_OF = [
  ['tutorial', 's1'], ['menu', 's2'], ['join', 's2'], ['connect', 's3'], ['loading', 's3'], ['tip', 's3'], ['howto', 's3'],
  ['lobby', 's4'], ['lobby.setting', 's5'], ['esc', 's5'], ['preset', 's5'], ['unit', 's5'], ['guide', 's5'], ['settings', 's5'],
  ['pregame', 's6'], ['hud', 's7'], ['item', 's7'], ['map', 's8'], ['room', 's8'], ['downed', 's9'], ['dead', 's9'],
  ['respawn', 's9'], ['end', 's10'],
];
const KIND = {
  gender: 'рід', rule: 'правило', 'less-text': 'менше тексту', clarity: 'ясність', consistency: 'однаковість',
  obvious: 'очевидне', word: 'одне слово', tone: 'тон', case: 'велика літера',
};
const FORM_UK = ['1', '2–4', '5+'];
const FORM_EN = ['1', '2+'];

class BuildError extends Error {}
const fail = (msg) => { throw new BuildError(msg); };
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const readText = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8').replace(/\r\n/g, '\n');
// Placeholders stand out as small boxes; the rest is escaped text.
const show = (s) => esc(s).replace(/\{([a-z_]+)\}/g, '<span class="cp-ph">$1</span>');
const screenOf = (key) => {
  let best = null;
  for (const [p, s] of SCREEN_OF) if ((key === p || key.startsWith(p + '.')) && (!best || p.length > best[0].length)) best = [p, s];
  return best ? best[1] : 'shared';
};
const num = (s) => String(s).replace(/^s/, '');

function texts(e) {
  if (!e.plural) {
    return `<span class="cp-uk tv-ToyTextOnLight" lang="uk">${show(e.uk[0])}</span><span class="cp-en tv-ToyTextMutedOnLight" lang="en">${show(e.en[0])}</span>`;
  }
  const forms = (lang, list, labels, cls) => `<span class="cp-${lang} cp-forms ${cls}" lang="${lang}">${list.map((f, i) => `<span class="cp-form"><small>${labels[i]}</small>${show(f)}</span>`).join('')}</span>`;
  return forms('uk', e.uk, FORM_UK, 'tv-ToyTextOnLight') + forms('en', e.en, FORM_EN, 'tv-ToyTextMutedOnLight');
}

function button(cls, attrs, label) {
  return `<button type="button" class="${cls}" ${attrs}><span>${label}</span><span class="tv-focus"></span></button>`;
}

function build() {
  const L = D.load(ROOT);
  if (L.errors.length) fail('the copy deck has errors; run node tools/copy/check.js\n' + L.errors.join('\n'));
  const entries = L.deck.entries;
  const byKey = new Map(entries.map((e) => [e.key, e]));
  const flags = L.flags.flags;
  const titles = L.titles;
  const screens = Object.keys(titles);
  if (screens.length !== 10) fail(`expected 10 wireframe screens, found ${screens.length}`);
  const where = (key) => {
    const own = screenOf(key);
    const on = (L.frames.used.get(key) || []).filter((s) => s && s !== own);
    const parts = [];
    if (own !== 'shared') parts.push('екран ' + num(own));
    if (on.length) parts.push((own === 'shared' ? 'екрани ' : 'також ') + on.map(num).join(', '));
    if (!L.frames.used.has(key)) parts.push('поза кадрами');
    return parts.join(' · ');
  };

  // ----- components CSS: only the variations the page uses -----
  const sys = api.load({ root: ROOT });
  const emitted = emitComponentsCss(sys).replace(/\r\n/g, '\n');
  const blocks = new Map();
  let cur = null;
  for (const l of emitted.split('\n')) {
    const h = /^\/\* (Toy[A-Za-z]+): /.exec(l);
    if (h) { cur = []; blocks.set(h[1], cur); }
    if (cur) cur.push(l);
  }
  const uiParts = [HEADER_UI];
  for (const name of USED) {
    const b = blocks.get(name);
    if (!b) fail(`emit-css: no variation ${name}`);
    while (b.length && !b[b.length - 1].trim()) b.pop();
    uiParts.push(b.join('\n'));
  }
  const uiCss = uiParts.join('\n') + '\n';

  // ----- the open questions -----
  const asked = L.flags.asked;
  const textsOf = (uk, en) => `<span class="cp-uk tv-ToyTextOnLight" lang="uk">${show(uk)}</span><span class="cp-en tv-ToyTextMutedOnLight" lang="en">${show(en)}</span>`;
  const rowsHtml = (rows, many) => rows.map((r) => {
    const k = many ? `<code class="cp-key">${esc(r.key)}</code>` : '';
    const t = r.uk ? textsOf(r.uk, r.en) : '<span class="cp-uk tv-ToyTextOnLight cp-remove">прибрати рядок</span>';
    return `<div class="cp-texts">${k}${t}</div>`;
  }).join('');
  // What a tap on an option saves as its text: the Ukrainian it writes, or what it does.
  const optText = (o) => (o.rows.length ? o.rows.map((r) => (r.uk ? r.uk : `прибрати ${r.key}`)).join(' / ') : o.label).slice(0, 300);
  const cards = flags.map((f) => {
    const many = f.keys.length > 1;
    const id = f.id.replace(/\./g, '-');
    const now = f.keys.map((k) => { const e = byKey.get(k); return { key: k, uk: e.uk[0], en: e.en[0] }; });
    const opts = f.options.map((o) => `<div class="cp-opt" data-opt="${o.id}"><div class="cp-opt-head"><b class="cp-letter">${o.id}</b>${o.label ? `<span class="tv-ToyTextOnLight cp-opt-label">${esc(o.label)}</span>` : ''}</div>`
      + (o.rows.length ? `<div class="cp-rows">${rowsHtml(o.rows, many)}</div>` : '')
      + (o.note ? `<p class="cp-note-txt tv-ToyTextMutedOnLight">${esc(o.note)}</p>` : '')
      + `<div class="cp-act">${button('tv-ToyButtonSecondary', `data-answer="${o.id}" data-text="${esc(optText(o))}"`, 'Беру цей')}</div></div>`).join('');
    const on = [...new Set(f.keys.map(screenOf).filter((x) => x !== 'shared').map(num))].sort((x, y) => x - y);
    const places = !many ? where(f.id) : on.length ? (on.length > 1 ? 'екрани ' : 'екран ') + on.join(', ') : 'спільне';
    return `<article class="tv-ToyPanelMenu cp-card cp-flag" data-context="light" id="f-${esc(f.id)}" data-key="${esc(f.id)}">`
      + `<div class="cp-head"><span class="tv-ToyChipNew"><span class="tv-ToyChipNewText">${esc(KIND[f.kind])}</span></span><code class="cp-key">${esc(f.id)}</code><span class="cp-where">${esc(places)}</span>${f.round === 'rejected' ? '<span class="cp-again">ще раз</span>' : ''}</div>`
      + `<p class="cp-why tv-ToyTextMutedOnLight">${esc(f.why)}</p>`
      + `<div class="cp-pair"><span class="cp-lbl">Зараз</span><div class="cp-rows cp-old">${rowsHtml(now, many)}</div></div>`
      + `<div class="cp-opts">${opts}</div>`
      + '<div class="cp-form-box">'
      + `<div class="cp-own"><label for="t-${id}">Інакше: свій варіант (не обовʼязково)</label><span class="tv-ToyField"><input class="cp-input" id="t-${id}" type="text" maxlength="300" data-text-input><span class="tv-focus"></span></span></div>`
      + `<div class="cp-note"><label for="n-${id}">Нотатка (не обовʼязково)</label><span class="tv-ToyField"><textarea class="cp-input" id="n-${id}" rows="2" maxlength="2000" data-note-input></textarea><span class="tv-focus"></span></span></div>`
      + `<div class="cp-act">${button('tv-ToyButtonSecondary', 'data-answer="other"', 'Інакше')}${button('tv-ToyButtonGhostOnLight', 'data-save', 'Зберегти нотатку')}</div>`
      + '<p class="cp-saved" data-saved></p><p class="cp-prev tv-ToyTextMutedOnLight" data-prev hidden></p>'
      + '</div></article>';
  }).join('\n');

  // ----- decided after round 1 -----
  const decided = L.flags.decided.map((d) => {
    const lines = d.keys.map((k) => {
      const e = byKey.get(k);
      return `<div class="cp-texts"><code class="cp-key">${esc(k)}</code>${e ? textsOf(e.uk[0], e.en[0]) : '<span class="cp-uk tv-ToyTextOnLight cp-remove">прибрано</span>'}</div>`;
    }).join('');
    return `<li class="cp-row"><p class="cp-how tv-ToyTextOnLight">${show(d.how)}</p>${lines}</li>`;
  }).join('');

  // ----- every string, per screen, to read -----
  const groups = new Map([...screens.map((s) => [s, []]), ['shared', []]]);
  for (const e of entries) groups.get(screenOf(e.key)).push(e);
  const asks = new Set(flags.flatMap((f) => f.keys));
  const row = (e) => `<li class="cp-row"><div class="cp-texts">${texts(e)}</div><div class="cp-meta"><code class="cp-key">${esc(e.key)}</code><span class="cp-where">${esc(where(e.key))}</span>${asks.has(e.key) ? '<span class="cp-tag">є питання</span>' : ''}</div></li>`;
  const screenSecs = [...groups].filter(([, list]) => list.length).map(([s, list]) => {
    const title = s === 'shared' ? 'Спільне для кількох екранів' : `${num(s)} · ${titles[s]}`;
    return `<h3 class="cp-sub">${esc(title)} <small>${list.length}</small></h3><ul class="cp-list">${list.map(row).join('')}</ul>`;
  }).join('\n');

  const plural = entries.filter((e) => e.plural).length;
  const rejected = flags.filter((f) => f.round === 'rejected').length;
  const style = (id, text) => `<style id="${id}">\n${text.replace(/\s+$/, '')}\n</style>`;
  const html = [
    '<!doctype html>',
    '<html lang="uk" data-text-size="default">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>Тексти гри</title>',
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    `<link rel="stylesheet" href="${FONT_LINK}">`,
    style('toy-tokens', readText('dist/css/toy-tokens.css')),
    style('cp-ui', uiCss),
    style('sc-page', readText('pages/components/page.css')),
    style('cp-page', readText('pages/copy/page.css')),
    '</head>',
    '<body>',
    '<main>',
    '<h1>Тексти гри: коло 2</h1>',
    `<p class="cp-rule"><b>Принцип.</b> ${esc(L.flags.principle)}</p>`,
    flags.length
      ? `<p class="sc-lead">Відкритих питань: ${flags.length}${rejected ? ` (${rejected} ще раз, бо ти хотів інакше)` : ''}. Тапни «Беру цей» біля варіанта або «Інакше» з нотаткою. Прийняте вже внесено й згорнуте внизу.</p>`
      : '<p class="sc-lead">Відкритих питань немає: усі відповіді внесено в колоду, вони згорнуті внизу.</p>',
    flags.length
      ? `<div class="cp-bar"><p class="cp-count">Відповідей: <b id="cp-done">0</b> з ${flags.length}</p>`
        + '<p class="cp-db" id="cp-db" data-state="wait">Перевіряю, чи можна тут зберегти відповідь…</p></div>'
        + `<section class="cp-sec" id="flags"><h2>Що вирішити <small>${flags.length}</small></h2>`
        + `<div class="cp-cards">${cards}</div></section>`
      : '',
    `<section class="cp-sec" id="decided"><details class="cp-fold"><summary>Вирішено <small>${L.flags.decided.length}</small></summary>`
      + `<div class="tv-ToyPanelMenu cp-card" data-context="light"><ul class="cp-list">${decided}</ul></div></details></section>`,
    `<section class="cp-sec" id="all"><details class="cp-fold"><summary>Усі рядки <small>${entries.length}</small></summary>`
      + `<div class="tv-ToyPanelMenu cp-card" data-context="light">${screenSecs}</div></details></section>`,
    '<div class="cp-summary" id="cp-summary" hidden><label for="cp-summary-text">Підсумок відповідей, щоб скопіювати в чат</label><textarea id="cp-summary-text" rows="5" readonly></textarea></div>',
    `<footer class="cp-foot">Зібрано з copy/strings.csv (${entries.length} ключів, ${plural} з множиною) і copy/flags.json. Правила: copy/README.md і docs/research/2026-10-05-ukrainian-localization/report.md. Заповнювачі в рамці (як <span class="cp-ph">name</span>) гра підставляє сама. Вигляд — токени Toy ${esc(sys.version)}.</footer>`,
    '</main>',
    `<script>\nvar ASKED = ${JSON.stringify(asked)};\n${readText('pages/copy/copy.js').replace(/\s+$/, '')}\n</script>`,
    '</body>',
    '</html>',
    '',
  ].join('\n');
  return [[OUT_UI, uiCss], [OUT_HTML, html]];
}

function main(argv) {
  const check = argv.includes('--check');
  const unknown = argv.filter((a) => a !== '--check');
  if (unknown.length) {
    console.error(`unknown argument ${unknown[0]}\nusage: node pages/copy/build.js [--check]`);
    return 2;
  }
  let outputs;
  try {
    outputs = build();
  } catch (e) {
    if (e instanceof BuildError || /^emit-css:|^tokens:/.test(e.message)) { console.error(`error: ${e.message}`); return 1; }
    throw e;
  }
  for (const [file, text] of outputs) if (/\r/.test(text)) { console.error(`error: ${file} would contain CR bytes`); return 1; }
  if (check) {
    const stale = [];
    for (const [file, text] of outputs) {
      let disk = null;
      try { disk = fs.readFileSync(path.join(ROOT, file), 'utf8'); } catch (e) { disk = null; }
      if (disk !== text) stale.push(`${file} (${disk === null ? 'missing' : 'differs'})`);
    }
    if (stale.length) { console.log(`stale: ${stale.join(', ')}; run node pages/copy/build.js`); return 1; }
    console.log(`up to date: ${outputs.map(([f]) => f).join(', ')}`);
    return 0;
  }
  for (const [file, text] of outputs) fs.writeFileSync(path.join(ROOT, file), text);
  const kb = (t) => `${Math.round(Buffer.byteLength(t) / 1024)} KB`;
  console.log(`wrote ${outputs.map(([f, t]) => `${f} (${kb(t)})`).join(', ')}`);
  return 0;
}

module.exports = { main };

if (require.main === module) process.exitCode = main(process.argv.slice(2));
