// The room-signs try-and-choose page (prime-game-ui#6, xperiaroco2/prime-game#255): the three room-sign systems drawn
// in pages/room-signs/systems/{a,b,c} (system.json, SVGs, LICENCES.json), each shown in the game and side by side
// with the others: the set, carrying a package, a corridor of doors, the map (M), the delivery spot, legibility at
// 64/32/24/16 px over the light and the dark world, and colour vision. The engineer takes one, mixes or writes a note.
//
//   node pages/room-signs/build.js          write signs-ui.css, signs-cvd.css and room-signs.html
//   node pages/room-signs/build.js --check  fail when any of them is stale
//
// signs-ui.css (lint profile "generated", tools/lint/targets.json) holds the components CSS of every variation the
// mock-ups' HUD and map use, emitted from the tokens by pages/components/emit-css.js. The world (corridor, rooms, the
// carried box) and the signs themselves are scenery and textures, not UI: inline SVG coloured from world.css, outside
// the lint like the page chrome (page.css). signs-cvd.css repaints the mock-ups for one colour vision: every colour
// they use (the --w-* scenery literals of world.css, ink and cream, and every --toy-* colour signs-ui.css reads) run
// through tools/a11y/cvd.js (Machado 2009; greyscale is its luminance) at build time, no CSS filters. It declares
// --toy-* overrides, which only the tokens file may, so it is outside the lint too: it is a simulated eye, not UI.
// Every SVG must be listed as own work in its system's LICENCES.json. Node 20, no packages.
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const HERE = __dirname;
const ROOT = path.resolve(HERE, '..', '..');
const api = require(path.join(ROOT, 'tools', 'tokens', 'api.js'));
const { emitComponentsCss } = require(path.join(ROOT, 'pages', 'components', 'emit-css.js'));
const wcag = require(path.join(ROOT, 'tools', 'lib', 'wcag.js'));

const OUT_UI = 'pages/room-signs/signs-ui.css';
const OUT_CVD = 'pages/room-signs/signs-cvd.css';
const OUT_HTML = 'pages/room-signs/room-signs.html';
const FONT_LINK = 'https://fonts.googleapis.com/css2?family=Comfortaa:wght@300..700&display=swap';
const HEADER_UI = '/* Generated by pages/room-signs/build.js from tools/tokens/api.js (pages/components/emit-css.js): the variations the room-signs mock-ups use. Do not edit. */';
const HEADER_CVD = '/* Generated by pages/room-signs/build.js: the mock-ups\' colours under each colour vision, through tools/a11y/cvd.js (Machado 2009 at full severity; grey = luminance). A simulated eye, not UI: outside the lint. Do not edit. */';

class BuildError extends Error {}
const fail = (msg) => { throw new BuildError(msg); };
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const readText = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8').replace(/\r\n/g, '\n');
const r1 = (n) => String(Math.round(n * 10) / 10);
const r4 = (n) => String(Math.round(n * 10000) / 10000);
const dec = (n, d) => n.toFixed(d).replace('.', ',');

// ---------- rooms and systems ----------

const ROOMS = ['storage', 'hall', 'kitchen', 'lab', 'office', 'lounge', 'workshop', 'server'];
const SHORT = { storage: 'Склад', hall: 'Хол', kitchen: 'Кухня', lab: 'Лабораторія', office: 'Офіс', lounge: 'Відпочинок', workshop: 'Майстерня', server: 'Серверна' };
const MAP_ORDER = ['storage', 'kitchen', 'lab', 'office', 'hall', 'lounge']; // the wireframes' map, 3 x 2
const MAP_LIT = 'storage';
const MAP_HERE = 'hall';
const DEFAULT_ROOM = 'kitchen';
const SIDS = ['a', 'b', 'c'];

// What the page says about each system (Ukrainian), from its system.json; the names and pitches are the designers'.
const COPY = {
  a: {
    what: { storage: 'три ящики сходинками', hall: 'годинник-кільце', kitchen: 'кухарський ковпак', lab: 'колба з бульбашками', office: 'настільна лампа', lounge: 'диван', workshop: 'молоток і ключ навхрест', server: 'серверна стійка' },
    plus: 'Один код, силует. Найдешевша: 8 піктограм, одна табличка і дві сцени на всі кімнати, жодного нового кольору.',
    minus: 'Запасного коду немає: якщо штамп не прочитався здалеку, треба підійти ближче. Кожна нова кімната мусить пройти той самий тест на схожість.',
    pack: 'Плитка зі штампом на всіх шести гранях; верхню грань бачиш, поки несеш.',
    door: 'Квадратна табличка 0,5 м стирчить зі стіни біля дверей, з обох боків той самий штамп.',
    map: 'Штамп 32 px над назвою кімнати.',
    spot: 'Кремовий килимок 1,2 м зі штампом і стійка з табличкою на висоті 1,3 м.',
  },
  b: {
    plus: 'Два коди без кольору: обрис таблички видно здалеку (19 px на 15 м), піктограма підтверджує зблизька.',
    minus: 'Піктограма в табличці дрібніша й читається десь до 5 м; більше деталей: вирізані таблички, килимок і стійка.',
    pack: 'Знак на всіх шести гранях, на верхній повернутий до того, хто несе. Сіре тіло коробки тут лише заглушка.',
    door: 'Вирізана табличка у формі кімнати (0,4 м) висить «прапорцем» біля дверей.',
    map: 'Знак 40 px поруч із назвою кімнати.',
    spot: 'Килимок у формі таблички кімнати і стійка зі знаком.',
  },
  c: {
    what: { storage: 'три ящики', hall: 'вокзальний годинник', kitchen: 'чайник', lab: 'колба', office: 'настільна лампа', lounge: 'диван', workshop: 'молоток навскіс', server: 'штепсельна вилка' },
    plus: 'Річ стирчить у коридор під прямим кутом, тож її видно в профіль здалеку: близько 56 px на 10 м. Скринька доставки скрізь однакова.',
    minus: 'Кожній кімнаті потрібна своя 3D-модель і стеля близько 3,3 м біля дверей; просто перед дверима річ видно з торця.',
    pack: 'Кремова коробка з чорнильним значком на всіх шести гранях.',
    door: 'Велика іграшкова річ (близько 0,8 м) висить на кронштейні під прямим кутом до стіни.',
    map: 'Малюнок на чорнильному значку 40 px поруч із назвою кімнати.',
    spot: 'Однакова низька широка скринька з прорізом у кожній кімнаті доставки; кімнату називає лише значок на ній.',
  },
};

function loadSystems() {
  const out = {};
  for (const sid of SIDS) {
    const dir = `pages/room-signs/systems/${sid}`;
    let json, lic;
    try { json = JSON.parse(readText(`${dir}/system.json`)); } catch (e) { fail(`${dir}/system.json: ${e.message}`); }
    try { lic = JSON.parse(readText(`${dir}/LICENCES.json`)); } catch (e) { fail(`${dir}/LICENCES.json: ${e.message}`); }
    const ids = (json.rooms || []).map((r) => r.id);
    if (ids.join() !== ROOMS.join()) fail(`${dir}/system.json: rooms ${ids.join(', ')}; expected ${ROOMS.join(', ')}`);
    const rooms = {};
    for (const r of json.rooms) {
      const takes = 'takes_deliveries' in r ? r.takes_deliveries : r.deliveries;
      if (typeof takes !== 'boolean') fail(`${dir}/system.json: room ${r.id} does not say whether it takes deliveries`);
      rooms[r.id] = { name: r.name_uk, takes, optional: !!r.optional, raw: r };
    }
    out[sid] = { id: sid, dir, json, lic, rooms, name: json.name_uk, pitch: json.pitch_uk };
  }
  for (const r of ROOMS) {
    const v = SIDS.map((s) => `${out[s].rooms[r].name}|${out[s].rooms[r].takes}|${out[s].rooms[r].optional}`);
    if (new Set(v).size !== 1) fail(`room ${r}: the systems disagree on its name, deliveries or being optional (${v.join(' / ')})`);
  }
  return out;
}

// ---------- SVG files as symbols ----------

const SVG_COLOURS = { '#2a1f33': 'var(--rs-ink)', '#fff4e2': 'var(--rs-cream)' };

function svgSource(sys, rel) {
  const entry = sys.lic[rel];
  if (!entry || !/^own work$/i.test(String(entry.licence))) fail(`${sys.dir}/${rel}: not recorded as own work in LICENCES.json`);
  const text = readText(`${sys.dir}/${rel}`);
  if (/<(script|image|foreignObject|text|style|a|use|filter|mask|linearGradient|radialGradient|pattern)\b|href=|\son[a-z]+=|url\(/i.test(text)) {
    fail(`${sys.dir}/${rel}: only plain shapes are inlined (no text, links, filters, masks, gradients or scripts)`);
  }
  return text;
}

// One symbol per file: the hex fills and strokes become var(--rs-ink) / var(--rs-cream) in a style attribute, so a
// colour-vision wrapper repaints every <use> of it through inheritance.
function symbolOf(id, text, where) {
  const m = /^\s*<svg\b([^>]*)>([\s\S]*)<\/svg>\s*$/.exec(text);
  if (!m) fail(`${where}: not one <svg> element`);
  const vb = /\bviewBox="0 0 ([\d.]+) ([\d.]+)"/.exec(m[1]);
  if (!vb) fail(`${where}: no viewBox "0 0 w h"`);
  const body = m[2].replace(/<([a-zA-Z]+)\b([^>]*?)(\/?)>/g, (all, tag, attrs, self) => {
    const style = [];
    const rest = attrs.replace(/\s(fill|stroke)="(#[0-9a-fA-F]{6})"/g, (a, prop, hex) => {
      const v = SVG_COLOURS[hex.toLowerCase()];
      if (!v) fail(`${where}: colour ${hex} is not the tokens' ink or cream`);
      style.push(`${prop}:${v}`);
      return '';
    });
    if (style.length && /\sstyle=/.test(rest)) fail(`${where}: a style attribute next to a colour`);
    return `<${tag}${rest}${style.length ? ` style="${style.join(';')}"` : ''}${self}>`;
  }).replace(/>\s+</g, '><').trim();
  if (/#[0-9a-fA-F]{3,8}\b/.test(body)) fail(`${where}: a colour outside fill and stroke`);
  return { id, w: Number(vb[1]), h: Number(vb[2]), body };
}

let HATCH_WINDOW = null;
function buildSymbols(S) {
  const sym = new Map();
  const add = (s) => { if (sym.has(s.id)) fail(`symbol ${s.id} twice`); sym.set(s.id, s); };
  const file = (sid, rel, id) => add(symbolOf(id, svgSource(S[sid], rel), `${S[sid].dir}/${rel}`));
  for (const r of ROOMS) {
    file('a', `icons/${r}.svg`, `rs-a-icon-${r}`);
    file('a', `faces/${r}.svg`, `rs-a-face-${r}`);
    file('b', `signs/${r}.svg`, `rs-b-sign-${r}`);
    file('b', `plates/${r}.svg`, `rs-b-plate-${r}`);
    file('c', `${r}.svg`, `rs-c-draw-${r}`);
  }
  file('c', 'frame-badge.svg', 'rs-c-frame');
  file('c', 'hatch.svg', 'rs-c-hatch');
  // The drop-off's badge window: its one square ink rect, where the room's badge is drawn in the spot scene.
  const win = /<rect x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" height="\3"[^>]*fill="#2a1f33"/.exec(readText(`${S.c.dir}/hatch.svg`));
  if (!win) fail(`${S.c.dir}/hatch.svg: no square ink badge window`);
  HATCH_WINDOW = { x: Number(win[1]), y: Number(win[2]), size: Number(win[3]) };
  file('c', 'bracket.svg', 'rs-c-bracket');
  // Composites (page only; the designers' files stay as they are): C's badge with its drawing, and the 0.45 m package
  // face of B (a 0.32 m sign on the box body, a grey placeholder) and of C (a 0.38 m badge on cream).
  for (const r of ROOMS) {
    add({ id: `rs-c-badge-${r}`, w: 64, h: 64, body: `<use href="#rs-c-frame" width="64" height="64"/><use href="#rs-c-draw-${r}" width="64" height="64"/>` });
    add({ id: `rs-b-pack-${r}`, w: 90, h: 90, body: `<rect width="90" height="90" style="fill:var(--w-box)"/><use href="#rs-b-sign-${r}" x="13" y="13" width="64" height="64"/>` });
    add({ id: `rs-c-pack-${r}`, w: 90, h: 90, body: `<rect width="90" height="90" style="fill:var(--rs-cream)"/><use href="#rs-c-badge-${r}" x="7" y="7" width="76" height="76"/>` });
  }
  return sym;
}

// Which symbol each system uses where.
const KIND = {
  pack: { a: 'rs-a-face', b: 'rs-b-pack', c: 'rs-c-pack' },   // a package face (90 units = 0.45 m)
  door: { a: 'rs-a-face', b: 'rs-b-sign', c: 'rs-c-draw' },   // what hangs at the door, seen down the corridor
  mark: { a: 'rs-a-icon', b: 'rs-b-sign', c: 'rs-c-badge' },  // the map tile's sign
  set: { a: 'rs-a-face', b: 'rs-b-sign', c: 'rs-c-badge' },   // the sign as printed
};
// The door sign's height in metres (system.json): A's plate, B's sign, C's prop figure (the cream object, 0.8 m).
const DOOR_M = { a: 0.5, b: 0.4, c: 0.8 };
// The height of the drawn box in metres: C's 64-unit drawing is 1.0 m, its figure about 0.8 m of it.
const DOOR_BOX_M = { a: 0.5, b: 0.4, c: 1.0 };

// ---------- the world: a pinhole camera at eye height, 704 px per metre at 1 m on a 1080p screen (as ground.md) ----------

const F = 704, CX = 960, CY = 540, EYE = 1.6;
const P = (x, y, z) => [CX + F * x / z, CY - F * (y - EYE) / z];
const pts = (list) => list.map((p) => `${r1(p[0])},${r1(p[1])}`).join(' ');
const poly = (cls, list) => `<polygon class="${cls}" points="${pts(list)}"/>`;
const line = (cls, a, b) => `<line class="${cls}" x1="${r1(a[0])}" y1="${r1(a[1])}" x2="${r1(b[0])}" y2="${r1(b[1])}"/>`;
const rectEl = (cls, R) => `<rect class="${cls}" x="${r1(R.x)}" y="${r1(R.y)}" width="${r1(R.w)}" height="${r1(R.h)}"/>`;
// A rectangle facing the camera at depth z, x from xa to xb, y from y0 to y1 (metres).
function screenRect(xa, xb, y0, y1, z) {
  const [x1, top] = P(Math.min(xa, xb), y1, z);
  const [x2, bottom] = P(Math.max(xa, xb), y0, z);
  return { x: x1, y: top, w: x2 - x1, h: bottom - top };
}
// A floor rectangle as the affine box between its near and far edges (a mock-up, not a true perspective).
function floorRect(cx, half, zNear, zFar) {
  const [l1, yn] = P(cx - half, 0, zNear), [rr1] = P(cx + half, 0, zNear);
  const [l2, yf] = P(cx - half, 0, zFar), [rr2] = P(cx + half, 0, zFar);
  return { x: (l1 + l2) / 2, y: yf, w: (rr1 + rr2 - l1 - l2) / 2, h: yn - yf };
}

let SYM = null;
function place(id, R, opts) {
  const o = opts || {};
  const s = SYM.get(id);
  if (!s) fail(`unknown symbol ${id}`);
  const sx = R.w / s.w, sy = R.h / s.h;
  const t = o.mirror ? `translate(${r1(R.x + R.w)} ${r1(R.y)}) scale(${r4(-sx)} ${r4(sy)})` : `translate(${r1(R.x)} ${r1(R.y)}) scale(${r4(sx)} ${r4(sy)})`;
  return `<use href="#${id}" width="${s.w}" height="${s.h}" transform="${t}"${o.swap ? ' data-swap=""' : ''}/>`;
}
// A sign in the page (not in a scene) at a fixed CSS size.
function icon(id, px, label, cls) {
  const s = SYM.get(id);
  if (!s) fail(`unknown symbol ${id}`);
  const h = Math.round(px * s.h / s.w);
  const a11y = label ? ` role="img" aria-label="${esc(label)}"` : ' aria-hidden="true"';
  return `<svg${cls ? ` class="${cls}"` : ''} width="${px}" height="${h}" viewBox="0 0 ${s.w} ${s.h}"${a11y}><use href="#${id}" width="${s.w}" height="${s.h}"/></svg>`;
}
// A sign inside a frame, sized in reference pixels by a class (rs-m32, rs-m40).
function frameIcon(id, cls, swap) {
  const s = SYM.get(id);
  return `<svg class="${cls}" viewBox="0 0 ${s.w} ${s.h}" aria-hidden="true"><use href="#${id}" width="${s.w}" height="${s.h}"${swap ? ' data-swap=""' : ''}/></svg>`;
}

// The shell of a box-shaped space: walls at x = ±w2, ceiling h, from zn to the back wall zb.
function shell(w2, h, zn, zb, floorZ, lampZ) {
  const out = [
    poly('wc', [P(-w2, h, zn), P(w2, h, zn), P(w2, h, zb), P(-w2, h, zb)]),
    poly('wf', [P(-w2, 0, zn), P(w2, 0, zn), P(w2, 0, zb), P(-w2, 0, zb)]),
    poly('wl', [P(-w2, 0, zn), P(-w2, h, zn), P(-w2, h, zb), P(-w2, 0, zb)]),
    poly('wr', [P(w2, 0, zn), P(w2, h, zn), P(w2, h, zb), P(w2, 0, zb)]),
    rectEl('wb', screenRect(-w2, w2, 0, h, zb)),
  ];
  for (const z of floorZ) out.push(line('wln', P(-w2, 0, z), P(w2, 0, z)));
  out.push(line('wln', P(-w2, 0, zn), P(-w2, 0, zb)), line('wln', P(w2, 0, zn), P(w2, 0, zb)));
  for (const z of lampZ) out.push(poly('wlt', [P(-0.35, h, z), P(0.35, h, z), P(0.35, h, z + 0.9), P(-0.35, h, z + 0.9)]));
  return out.join('');
}

// The corridor: 3.2 m wide, 3.6 m high (system C needs about 3.3 m by the doors), four doors.
const CW2 = 1.6, CH = 3.6;
const DOORS = [{ room: 'kitchen', side: -1, z: 4 }, { room: 'lab', side: 1, z: 7.5 }, { room: 'office', side: -1, z: 12 }, { room: 'lounge', side: 1, z: 18 }];
const signZ = (d) => d.z - 0.2; // the blade hangs on the near (latch) side of the frame

function doorSign(sid, d) {
  const zs = signZ(d);
  const wall = d.side * CW2;
  const X = (out) => wall - d.side * out;
  if (sid === 'a') {
    return rectEl('wink', screenRect(X(0), X(0.07), 2.06, 2.44, zs)) + place(`rs-a-face-${d.room}`, screenRect(X(0.06), X(0.56), 2.0, 2.5, zs));
  }
  if (sid === 'b') {
    return rectEl('wink', screenRect(X(0), X(0.32), 2.17, 2.22, zs)) + place(`rs-b-sign-${d.room}`, screenRect(X(0.1), X(0.5), 1.8, 2.2, zs));
  }
  return place('rs-c-bracket', screenRect(X(0), X(1.2), 3.05, 3.5, zs), { mirror: d.side > 0 })
    + place(`rs-c-draw-${d.room}`, screenRect(X(0.15), X(0.15 + DOOR_BOX_M.c), 2.15, 2.15 + DOOR_BOX_M.c, zs));
}

function corridor(sid) {
  const parts = [shell(CW2, CH, 0.3, 32, [2.5, 4.2, 6.5, 9.5, 13.5, 19, 26], [2.6, 6.5, 11.5, 18, 26])];
  for (const d of DOORS) {
    const x = d.side * CW2;
    parts.push(poly('wdf', [P(x, 0, d.z - 0.08), P(x, 2.18, d.z - 0.08), P(x, 2.18, d.z + 1.08), P(x, 0, d.z + 1.08)]));
    parts.push(poly('wd', [P(x, 0, d.z), P(x, 2.1, d.z), P(x, 2.1, d.z + 1), P(x, 0, d.z + 1)]));
  }
  for (const d of DOORS.slice().sort((p, q) => q.z - p.z)) parts.push(doorSign(sid, d));
  return parts.join('');
}

// The carried box, drawn flat (top face foreshortened to 0.57, the 35° view of ground.md) at the bottom of the view;
// a 0.32 m sign field is about 185 px wide there, as the designers measured.
function carriedBox(sid, room) {
  const id = `${KIND.pack[sid]}-${room}`;
  const W = 260, X0 = CX - W / 2, TOP = 812, TH = Math.round(W * 0.57);
  return `<g>${place(id, { x: X0, y: TOP, w: W, h: TH }, { swap: true })}${place(id, { x: X0, y: TOP + TH, w: W, h: W }, { swap: true })}`
    + `<rect class="wedge" x="${X0}" y="${TOP}" width="${W}" height="${TH + W}"/>${line('wedge', [X0, TOP + TH], [X0 + W, TOP + TH])}</g>`;
}

function spotScene(sid, room) {
  const parts = [shell(3.2, 3.0, 0.3, 5.5, [1.5, 2.4, 3.4, 4.4], [1.6, 3.6])];
  const sx = 1.3;
  if (sid === 'a') {
    parts.push(place(`rs-a-face-${room}`, floorRect(sx, 0.6, 3.0, 4.2), { swap: true }));
    parts.push(rectEl('wink', screenRect(sx - 0.03, sx + 0.03, 0, 1.06, 4.25)));
    parts.push(place(`rs-a-face-${room}`, screenRect(sx - 0.25, sx + 0.25, 1.05, 1.55, 4.25), { swap: true }));
  } else if (sid === 'b') {
    parts.push(place(`rs-b-plate-${room}`, floorRect(sx, 0.6, 3.0, 4.2), { swap: true }));
    parts.push(rectEl('wink', screenRect(sx - 0.03, sx + 0.03, 0, 0.96, 4.25)));
    parts.push(place(`rs-b-sign-${room}`, screenRect(sx - 0.16, sx + 0.16, 0.94, 1.26, 4.25), { swap: true }));
  } else {
    // hatch.svg (the drop-off): 1 unit = 0.02 m, the bottom of its view box on the floor, against the back wall; the
    // badge in its dark square (HATCH_WINDOW, 18 units = 0.36 m).
    const h = SYM.get('rs-c-hatch'), w = HATCH_WINDOW;
    const z = 5.45, s = F * 0.02 / z;
    const [X, Y] = P(sx - h.w * 0.01, h.h * 0.02, z);
    parts.push(`<g transform="translate(${r1(X)} ${r1(Y)}) scale(${r4(s)})"><use href="#rs-c-hatch" width="${h.w}" height="${h.h}"/>`
      + `<use href="#rs-c-badge-${room}" x="${w.x}" y="${w.y}" width="${w.size}" height="${w.size}" data-swap=""/></g>`);
  }
  parts.push(carriedBox(sid, room));
  return parts.join('');
}

const world = (inner) => `<svg class="rs-world" viewBox="0 0 1920 1080" preserveAspectRatio="none" aria-hidden="true">${inner}</svg>`;
const frame = (label, inner) => `<div class="rs-scroll"><div class="rs-frame" role="img" aria-label="${esc(label)}">${inner}</div></div>`;

let HEALTH_STEP = '16';
function hud() {
  return '<div class="rs-layer">'
    + '<div class="rs-at rs-at-top"><div class="tv-ToyPlate"><span class="tv-ToyTimer">07:22</span></div></div>'
    + '<div class="rs-at rs-at-mid"><div class="tv-ToyCrosshair"></div></div>'
    + '<div class="rs-at rs-at-bl"><div class="tv-ToyBarTrack"><div class="tv-ToyBarStamina" style="--value: 0.9"><i class="tv-fill"></i></div></div>'
    + `<div class="tv-ToyBarTrack"><div class="tv-ToyBarHealth" data-step="${HEALTH_STEP}" style="--value: 0.8"><i class="tv-fill"></i></div></div></div>`
    + '<div class="rs-at rs-at-br"><div class="tv-ToySlotActive tv-wide"><span class="tv-ToySlotText">Пакунок</span></div>'
    + '<div class="tv-ToySlot"><span class="tv-ToySlotTextEmpty">пояс</span></div></div>'
    + '</div>';
}

function carryFrame(S, sid) {
  return frame(`${S[sid].name}: несеш пакунок коридором`, world(corridor(sid) + carriedBox(sid, DEFAULT_ROOM)) + hud());
}
function doorFrame(S, sid) {
  return frame(`${S[sid].name}: коридор із чотирма дверима`, world(corridor(sid)));
}
function spotFrame(S, sid) {
  return frame(`${S[sid].name}: місце доставки з порога кімнати`, world(spotScene(sid, DEFAULT_ROOM)));
}
// A map tile as each system draws it: A's stamp (32 px) over the name, B's sign and C's badge (40 px) beside it.
function mapTile(S, sid, r, here) {
  const col = sid === 'a';
  const zone = r === MAP_LIT ? '<div class="rs-zone-at"><div class="tv-ToyMapZone"></div></div>' : '';
  const chip = here && r === MAP_HERE ? '<div class="rs-here"><div class="tv-ToyChipPlate"><span class="tv-ToyHudCaption">ти тут</span></div></div>' : '';
  return `<div class="tv-ToyMapRoom rs-tile${col ? ' rs-tile-col' : ''}">${zone}${frameIcon(`${KIND.mark[sid]}-${r}`, col ? 'rs-m32' : 'rs-m40')}`
    + `<span class="tv-ToyMapRoomText">${esc(S[sid].rooms[r].name)}</span>${chip}</div>`;
}
// Two tiles at one reference pixel per CSS pixel, outside a frame: about their size on a 1080p screen.
function mapTrue(S, sid) {
  return `<div class="rs-true"><div class="tv-ToyMapBoard" data-context="light"><div class="rs-true-grid">${[MAP_LIT, DEFAULT_ROOM].map((r) => mapTile(S, sid, r, false)).join('')}</div></div></div>`;
}
function mapFrame(S, sid) {
  const tiles = MAP_ORDER.map((r) => mapTile(S, sid, r, true)).join('');
  return frame(`${S[sid].name}: мапа (M)`, world(corridor(sid))
    + '<div class="rs-fill"><div class="tv-ToyBackdrop"></div></div>'
    + `<div class="rs-layer"><div class="rs-at rs-at-mid"><div class="tv-ToyMapBoard" data-context="light"><div class="rs-board-grid">${tiles}</div></div></div></div>`);
}

// ---------- colours: tokens, world, visions ----------

const VISIONS = [['normal', 'звичайний зір'], ['protan', 'протанопія'], ['deutan', 'дейтеранопія'], ['tritan', 'тританопія'], ['grey', 'відтінки сірого']];

function loadCvd() {
  // tools/a11y/cvd.js is a script, not a module: run it unchanged with its printing silenced and take its functions.
  const src = readText('tools/a11y/cvd.js');
  const out = vm.runInNewContext(`${src}\n;({ simulateLin, toLin, toSrgb, linToLab, de2000 });`, { console: { log() {} } }, { filename: 'tools/a11y/cvd.js', timeout: 60000 });
  for (const k of ['simulateLin', 'toLin', 'toSrgb', 'linToLab', 'de2000']) if (typeof out[k] !== 'function') fail(`tools/a11y/cvd.js: no ${k}`);
  return out;
}

function parseColour(v) {
  let m = /^#([0-9a-fA-F]{6})$/.exec(v);
  if (m) return { rgb: wcag.fromHex(v).slice(0, 3), a: null };
  m = /^rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)$/.exec(v);
  if (m) return { rgb: [m[1], m[2], m[3]].map((x) => Number(x) / 255), a: Number(m[4]) };
  return null;
}

function rootVars(css, prefix, where) {
  const m = /:root \{\n([\s\S]*?)\n\}/.exec(css);
  if (!m) fail(`${where}: no :root block`);
  const map = new Map();
  for (const l of m[1].split('\n')) {
    const d = /^\s*(--[\w-]+):\s*(.+?);\s*$/.exec(l);
    if (d && d[1].startsWith(prefix)) map.set(d[1], d[2]);
  }
  return map;
}

function resolver(maps) {
  const get = (name, depth) => {
    if (depth > 30) fail(`${name}: alias loop`);
    for (const m of maps) if (m.has(name)) {
      const v = m.get(name);
      const a = /^var\((--[\w-]+)\)$/.exec(v);
      return a ? get(a[1], depth + 1) : v;
    }
    fail(`${name}: not declared`);
    return null;
  };
  return (name) => get(name, 0);
}

function simulate(cvd, rgb, vision) {
  return cvd.simulateLin(rgb.map(cvd.toLin), vision).map(cvd.toSrgb);
}
function colourText(c, rgb) {
  if (c.a === null) return wcag.toHex(rgb);
  return `rgba(${rgb.map((x) => Math.round(Math.min(1, Math.max(0, x)) * 255)).join(', ')}, ${c.a})`;
}

// ---------- the second question: where a package is delivered (prime-game#255) ----------

// A room seen from above in the Toy look, the same for every sign system: a neutral sign (an ink square with a cream
// dot) stands for whichever system is chosen. "one": one wide drop-off takes all of the room's packages; "many": a few
// small spots, any free one takes a package of the room. Plain SVG coloured by page.css (.rs-plan), no text inside.
const BINDINGS = ['one', 'many'];
function planSign(x, y, size) {
  const r = Math.round(size * 0.22 * 10) / 10;
  return `<rect class="pn" x="${x}" y="${y}" width="${size}" height="${size}" rx="${Math.round(size / 4)}"/>`
    + `<circle class="pc" cx="${x + size / 2}" cy="${y + size / 2}" r="${r}"/>`;
}
// A package from above: a cream box with a strip of tape (its sign is too small to draw at this scale).
function planBox(x, y, size) {
  const t = Math.round(size * 0.2);
  return `<rect class="pk" x="${x}" y="${y}" width="${size}" height="${size}" rx="5"/>`
    + `<rect class="pn" x="${x}" y="${y + (size - t) / 2}" width="${size}" height="${t}"/>`;
}
function planPlayer(x, y) {
  return `<circle class="pp" cx="${x}" cy="${y}" r="16"/>${planBox(x - 13, y - 46, 26)}`;
}
function plan(kind, label) {
  const room = '<rect class="pf" x="8" y="8" width="304" height="174" rx="18"/>'
    + '<rect class="pg" x="34" y="176" width="56" height="10"/>'
    + planSign(98, 171, 22);
  let inner = '';
  if (kind === 'one') {
    inner = '<rect class="pd" x="74" y="24" width="172" height="50" rx="12"/>' + planSign(86, 36, 26)
      + planBox(124, 35, 28) + planBox(160, 35, 28) + planBox(196, 35, 28) + planPlayer(160, 140);
  } else {
    const spots = [[62, 52, true], [258, 52, false], [258, 132, true], [160, 52, false]];
    inner = spots.map(([x, y, full]) => `<circle class="pd" cx="${x}" cy="${y}" r="24"/>`
      + (full ? planBox(x - 15, y - 15, 30) : planSign(x - 10, y - 10, 20))).join('') + planPlayer(160, 148);
  }
  return `<svg class="rs-plan" viewBox="0 0 320 196" role="img" aria-label="${esc(label)}">${room}${inner}</svg>`;
}

// ---------- the page ----------

function build() {
  const S = loadSystems();
  SYM = buildSymbols(S);
  const sys = api.load({ root: ROOT });
  const health = sys.variants.find((v) => v.variation === 'ToyBarHealth');
  const steps = health && health.ramp ? health.ramp.steps.value.value : 0;
  if (!steps) fail('tokens: ToyBarHealth has no ramp steps');
  HEALTH_STEP = String(Math.floor(0.8 * steps + 0.5)).padStart(2, '0');
  const cvd = loadCvd();
  const roomName = (r) => S.a.rooms[r].name;
  const delivery = ROOMS.filter((r) => S.a.rooms[r].takes);

  // ----- components CSS: only the variations the mock-ups use -----
  const USED = ['ToyBackdrop', 'ToyBarTrack', 'ToyBarStamina', 'ToyBarHealth', 'ToyChipPlate', 'ToyCrosshair', 'ToyHudCaption',
    'ToyMapBoard', 'ToyMapRoom', 'ToyMapRoomText', 'ToyMapZone', 'ToyPlate', 'ToySlot', 'ToySlotActive', 'ToySlotText',
    'ToySlotTextEmpty', 'ToyTimer'];
  const emitted = emitComponentsCss(sys).replace(/\r\n/g, '\n');
  const blocks = new Map();
  let cur = null;
  for (const l of emitted.split('\n')) {
    const h = /^\/\* (Toy[A-Za-z]+): /.exec(l);
    if (h) { cur = []; blocks.set(h[1], cur); }
    if (cur) cur.push(l);
  }
  const uiParts = [HEADER_UI];
  for (const name of USED) {
    const b = blocks.get(name);
    if (!b) fail(`emit-css: no variation ${name}`);
    while (b.length && !b[b.length - 1].trim()) b.pop();
    uiParts.push(b.join('\n'));
  }
  const uiCss = uiParts.join('\n') + '\n';

  // ----- colour visions -----
  const tokensCss = readText('dist/css/toy-tokens.css');
  const worldCss = readText('pages/room-signs/world.css');
  const toyVars = rootVars(tokensCss, '--toy-', 'dist/css/toy-tokens.css');
  const worldVars = rootVars(worldCss, '--', 'pages/room-signs/world.css');
  const resolve = resolver([toyVars, worldVars]);
  const names = [...worldVars.keys()];
  for (const n of [...new Set([...uiCss.matchAll(/var\((--toy-[\w-]+)\)/g)].map((m) => m[1]))].sort()) names.push(n);
  const colours = [];
  for (const n of names) {
    const c = parseColour(resolve(n));
    if (c) colours.push([n, c]);
    else if (n.startsWith('--w-') || n.startsWith('--rs-')) fail(`world.css: ${n} is not a #rrggbb colour`);
  }
  const cvdParts = [HEADER_CVD];
  for (const [v] of VISIONS.slice(1)) {
    cvdParts.push(`.rs-v-${v} {`);
    for (const [n, c] of colours) cvdParts.push(`  ${n}: ${colourText(c, simulate(cvd, c.rgb, v))};`);
    cvdParts.push('}');
  }
  const cvdCss = cvdParts.join('\n') + '\n';

  // The numbers under the colour-vision section: the sign's own pair, and the sign on a lit map tile.
  const ink = parseColour(resolve('--rs-ink')).rgb;
  const cream = parseColour(resolve('--rs-cream')).rgb;
  const zone = parseColour(resolve('--toy-map-zone-panel-bg-color'));
  const tile = parseColour(resolve('--toy-map-room-panel-bg-color')).rgb;
  const lit = wcag.composite(zone.rgb.concat(zone.a === null ? 1 : zone.a), tile.concat(1)).slice(0, 3);
  const pairRow = (label, a, b) => {
    const cells = VISIONS.map(([v]) => {
      const sa = simulate(cvd, a, v), sb = simulate(cvd, b, v);
      const d = cvd.de2000(cvd.linToLab(sa.map(cvd.toLin)), cvd.linToLab(sb.map(cvd.toLin)));
      return `<td>${dec(wcag.ratio(sa, sb), 1)}:1 · ΔE ${dec(d, 0)}</td>`;
    });
    return `<tr><th scope="row">${esc(label)}</th>${cells.join('')}</tr>`;
  };
  const cvdTable = '<div class="rs-table-scroll"><table class="rs-cvd-table"><thead><tr><th scope="col">пара</th>'
    + VISIONS.map(([, l]) => `<th scope="col">${esc(l)}</th>`).join('') + '</tr></thead><tbody>'
    + pairRow('знак: чорнило на кремі (усі три системи)', ink, cream)
    + pairRow('знак на підсвіченій плитці мапи', ink, lit)
    + '</tbody></table></div>';

  // ----- sections -----
  const head = (sid) => `<h3 class="rs-col-head"><span class="rs-letter">${sid.toUpperCase()}</span>${esc(S[sid].name)}</h3>`;
  const tri = (fn) => `<div class="rs-tri">${SIDS.map((sid) => `<article class="rs-col">${head(sid)}${fn(sid)}</article>`).join('')}</div>`;
  const section = (id, title, intro, body) => `<section class="rs-sec" id="${id}"><h2>${esc(title)}</h2>${intro ? `<p class="rs-intro">${intro}</p>` : ''}${body}</section>`;
  const roomSpan = `<span data-room-name>${esc(roomName(DEFAULT_ROOM))}</span>`;
  const what = (sid, r) => {
    if (COPY[sid].what) return COPY[sid].what[r];
    const raw = S[sid].rooms[r].raw;
    return `${raw.shape.name_uk} · ${raw.icon_uk}`;
  };

  const overview = tri((sid) => {
    const fig = (id, cap) => `<figure class="rs-tile-light">${icon(id, 64, `${cap}: ${roomName('kitchen')}`)}<figcaption>${esc(cap)}</figcaption></figure>`;
    return `<p class="rs-cap"><b>${esc(S[sid].pitch)}</b></p>`
      + `<div class="rs-hero">${fig(`${KIND.pack[sid]}-kitchen`, 'пакунок')}${fig(`${KIND.door[sid]}-kitchen`, 'двері')}${fig(`${KIND.mark[sid]}-kitchen`, 'мапа')}</div>`
      + `<ul class="rs-list"><li class="rs-plus">${esc(COPY[sid].plus)}</li><li class="rs-minus">${esc(COPY[sid].minus)}</li></ul>`;
  });

  const setBody = tri((sid) => `<div class="rs-set">${ROOMS.map((r) => {
    const room = S[sid].rooms[r];
    const flags = [];
    if (!room.takes) flags.push('без доставок');
    if (room.optional) flags.push('якщо буде на мапі');
    return `<figure class="rs-item"><div class="rs-item-sign rs-tile-light">${icon(`${KIND.set[sid]}-${r}`, 64, `${room.name}: ${what(sid, r)}`)}</div>`
      + `<b>${esc(room.name)}</b><span>${esc(what(sid, r))}</span>${flags.map((f) => `<em>${esc(f)}</em>`).join('')}</figure>`;
  }).join('')}</div>`);

  const carryBody = tri((sid) => carryFrame(S, sid) + `<p class="rs-cap">Пакунок до: <b>${roomSpan}</b>. ${esc(COPY[sid].pack)}</p>`);

  const distances = (sid) => `<ul class="rs-dist">${DOORS.map((d) => `<li><b>${esc(SHORT[d.room])}</b>${dec(signZ(d), 1)} м<span>${Math.round(F * DOOR_M[sid] / signZ(d))} px</span></li>`).join('')}</ul>`;
  const doorBody = tri((sid) => doorFrame(S, sid) + distances(sid) + `<p class="rs-cap">${esc(COPY[sid].door)}</p>`);

  const mapBody = tri((sid) => mapFrame(S, sid) + `<p class="rs-cap">${esc(COPY[sid].map)} Нижче дві плитки в натуральну величину екрана 1080p.</p>` + mapTrue(S, sid));

  const spotBody = tri((sid) => spotFrame(S, sid) + `<p class="rs-cap">Пакунок до: <b>${roomSpan}</b>. ${esc(COPY[sid].spot)}</p>`);

  const SIZES = [64, 32, 24, 16];
  const legBlock = (sid, cls, title) => `<div class="rs-leg ${cls}"><p class="rs-leg-title">${esc(title)}</p>`
    + SIZES.map((px) => `<div class="rs-leg-row"><span class="rs-leg-size">${px} px <small>≈ ${dec(F * DOOR_BOX_M[sid] / px, 1)} м до дверей</small></span>`
      + ROOMS.map((r) => icon(`${KIND.door[sid]}-${r}`, px, roomName(r))).join('') + '</div>').join('') + '</div>';
  const legBody = tri((sid) => legBlock(sid, 'rs-leg-light', 'світлий світ #C9C9C9') + legBlock(sid, 'rs-leg-dark', 'темний світ #979797')
    + `<p class="rs-names">Зліва направо: ${esc(ROOMS.map((r) => SHORT[r]).join(', '))}.</p>`);

  const visBar = '<div class="rs-vis-bar"><span class="rs-bar-label">Сцени нижче:</span><div class="rs-seg" role="group" aria-label="зір">'
    + VISIONS.map(([v, l], i) => `<button type="button" data-vision="${v}" aria-pressed="${i === 0 ? 'true' : 'false'}">${esc(l)}</button>`).join('') + '</div></div>';
  const strip = (sid) => `<div class="rs-strip">${VISIONS.map(([v, l]) => `<div class="rs-strip-row${v === 'normal' ? '' : ` rs-v-${v}`}"><span>${esc(l)}</span><div>`
    + delivery.map((r) => icon(`${KIND.pack[sid]}-${r}`, 30, `${l}: ${roomName(r)}`)).join('') + '</div></div>').join('')}</div>`;
  const cvdBody = cvdTable + visBar + tri((sid) => `<div class="rs-cvd-target">${carryFrame(S, sid)}${mapFrame(S, sid)}</div>`
    + `<p class="rs-cap">Поруч: грані пакунків для всіх ${delivery.length} кімнат доставки.</p>${strip(sid)}`);

  const pick = `<p class="rs-saved" id="rs-saved">ще без відповіді</p><div class="rs-tri">${SIDS.map((sid) => `<article class="rs-col rs-opt" data-o="${sid}">${head(sid)}`
    + `<div class="rs-pick-signs rs-tile-light">${delivery.slice(0, 4).map((r) => icon(`${KIND.set[sid]}-${r}`, 48, roomName(r))).join('')}</div>`
    + `<p class="rs-cap">${esc(COPY[sid].plus)}</p>`
    + `<div class="rs-act"><button type="button" class="rs-btn rs-take" data-take="${sid}">Беру цю систему</button><span class="rs-chosen">✓ ваш вибір</span></div></article>`).join('')}</div>`
    + '<article class="rs-col rs-opt rs-mix" data-o="mix"><h3 class="rs-col-head"><span class="rs-letter">+</span>Змішати</h3>'
    + '<p class="rs-cap">Частина однієї системи з частиною іншої: наприклад, форми табличок B зі штампами A, або речі C на дверях і штампи A на пакунках. Напишіть у нотатці нижче, що з чим.</p>'
    + '<div class="rs-act"><button type="button" class="rs-btn rs-take" data-take="mix">Змішати</button><span class="rs-chosen">✓ ваш вибір</span></div>'
    + '<p class="rs-hint" id="rs-mix-hint" hidden>Спершу напишіть у нотатці, що з чим змішати, а тоді натисніть «Змішати» ще раз.</p></article>'
    + '<div class="rs-note"><label for="rs-note">Нотатка (не обовʼязково)</label><textarea id="rs-note" rows="3" data-note-input></textarea>'
    + '<div class="rs-note-act"><button type="button" class="rs-btn rs-btn-quiet" data-save-note>Зберегти нотатку</button></div></div>'
    + '<details class="rs-rooms"><summary>Нотатки до окремих кімнат (не обовʼязково)</summary><div class="rs-room-grid">'
    + ROOMS.map((r) => `<div class="rs-room-note" data-room-note="${r}" data-name="${esc(roomName(r))}"><label for="rs-room-${r}">`
      + SIDS.map((sid) => icon(`${KIND.set[sid]}-${r}`, 24)).join('') + `${esc(roomName(r))}</label>`
      + `<textarea id="rs-room-${r}" rows="2"></textarea><div class="rs-room-act"><button type="button" class="rs-btn rs-btn-quiet" data-save-room>Зберегти</button>`
      + '<span class="rs-room-saved" data-room-saved></span></div></div>').join('')
    + '</div></details>';

  // The second question: one drop-off per room, or several spots of which any free one takes the room's package.
  const BIND_COPY = {
    one: { title: 'Одна точка на кімнату', tag: 'радимо', alt: 'План кімнати згори: біля стіни одна широка точка доставки зі знаком кімнати, на ній три пакунки; гравець несе ще один.',
      text: 'Одна широка точка біля стіни приймає всі пакунки цієї кімнати (за раунд їх 2–3). Найпростіше прочитати: один знак на кімнату, одне місце, куди нести.' },
    many: { title: 'Кілька місць у кімнаті', tag: '', alt: 'План кімнати згори: чотири малі місця зі знаком кімнати, на двох уже стоять пакунки; гравець несе пакунок до вільного.',
      text: 'Три-чотири малі місця по кімнаті; будь-яке вільне приймає пакунок цієї кімнати. Знаків у кімнаті більше, і вільне місце ще треба знайти.' },
  };
  const bindBody = '<p class="rs-saved" id="rs-bind-saved">ще без відповіді</p><div class="rs-tri">'
    + BINDINGS.map((b, i) => `<article class="rs-col rs-opt" data-b="${b}"><h3 class="rs-col-head"><span class="rs-letter">${'аб'[i]}</span>${esc(BIND_COPY[b].title)}`
      + `${BIND_COPY[b].tag ? ` <span class="rs-tag">${esc(BIND_COPY[b].tag)}</span>` : ''}</h3>`
      + plan(b, BIND_COPY[b].alt) + `<p class="rs-cap">${esc(BIND_COPY[b].text)}</p>`
      + `<div class="rs-act"><button type="button" class="rs-btn rs-bind" data-bind="${b}">Беру це</button><span class="rs-chosen">✓ ваш вибір</span></div></article>`).join('')
    + '</div><p class="rs-cap rs-legend">На плані: темний квадрат із крапкою — знак кімнати (у будь-якій системі); кремові коробки зі смужкою — пакунки цієї кімнати; зелене коло — гравець із пакунком. Біля дверей той самий знак, що на точці доставки.</p>'
    + '<div class="rs-note"><label for="rs-bind-note">Нотатка (не обовʼязково)</label><textarea id="rs-bind-note" rows="2"></textarea>'
    + '<div class="rs-note-act"><button type="button" class="rs-btn rs-btn-quiet" data-save-bind-note>Зберегти нотатку</button></div></div>'
    + '<div class="rs-summary" id="rs-summary" hidden><label for="rs-summary-text">Підсумок обох відповідей, щоб скопіювати в чат</label><textarea id="rs-summary-text" rows="4" readonly></textarea></div>';

  // Small technical calls the agent made itself; the engineer may veto any of them in a note.
  const issue = (n) => `<a href="https://github.com/xperiaroco2/prime-game/issues/${n}">prime-game#${n}</a>`;
  const AGENT = [
    [`Мапа: наведення на задачу «Доставка» підсвічує лише ${esc(roomName(MAP_LIT))}.`, 'Якби світилися кімнати, що чекають пакунків, підсвітка стала б маркером цілі.'],
    ['HUD: слот у руці не повторює знак пакунка, який несеш.', 'На HUD жодних підказок; знак і так видно на верхній грані коробки.'],
    ['Перехрестя коридорів: жодних знаків-напрямків.', 'Знаки позначають кімнати, а не маршрути.'],
    [`${esc(roomName('storage'))} і ${esc(roomName('hall'))} пакунків не приймають.`, `На Складі пакунки беруть, Хол перетинають усі, тож точка там була б задарма. Пропозиція для мапи дизайнера (${issue(146)}).`],
  ];
  const agentBody = `<ul class="rs-agent">${AGENT.map(([what, why]) => `<li><b>${what}</b> <small class="rs-by">(агент)</small><span>Чому: ${why}</span></li>`).join('')}</ul>`
    + `<p class="rs-cap">Сам перелік кімнат (${ROOMS.map((r) => esc(roomName(r))).join(', ')}) — теж лише пропозиція для мапи дизайнера, ${issue(146)}. Не згодні з чимось — напишіть у нотатці вище.</p>`;

  const sections = [
    section('systems', 'Три системи коротко', 'Кожну систему малювали окремо, незалежно від інших. Нижче одна й та сама кімната (Кухня) у трьох місцях: на пакунку, біля дверей і на мапі.', overview),
    section('set', 'Набір знаків', `Вісім кімнат: шість для першої мапи і дві, якщо на мапі буде для них місце. Склад і Хол пакунків не приймають, тож на коробках їхніх знаків немає. Перелік кімнат — пропозиція для мапи дизайнера (${issue(146)}).`, setBody),
    section('carry', 'Несеш пакунок', 'Від першої особи, як на вайрфреймі 7: пакунок у руках, коридор попереду. Слова на коробці немає; HUD не каже, куди йти. Кімнату пакунка можна змінити вгорі.', carryBody),
    section('doors', 'Двері в коридорі', 'Той самий коридор без пакунка. Знаки висять під прямим кутом до стіни, тож їх видно вздовж коридору. Під кадром: відстань до знака і його висота на екрані 1080p.', doorBody),
    section('map', 'Мапа (M)', `Кожна кімната завжди зі своїм знаком, хоч що ти несеш. Жовтим підсвічено ${esc(roomName(MAP_LIT))}, ніби навели на задачу «Доставка»: світиться лише він (вирішив агент, див. унизу).`, mapBody),
    section('spot', 'Місце доставки', 'Вигляд з порога кімнати з пакунком у руках. Пакунок і місце мають той самий знак; більше нічого не світиться й не підказує.', spotBody),
    section('legibility', 'Чи читається', 'Знак, як він висить біля дверей, розміром 64, 32, 24 і 16 px на світлому і темному світі-заглушці. Поруч: з якої відстані він такий на екрані 1080p.', legBody),
    section('vision', 'Дальтонізм', 'Ті самі сцени для протанопії, дейтеранопії, тританопії й у відтінках сірого. Кольори пораховано наперед через tools/a11y/cvd.js (Machado 2009, повна сила), без CSS-фільтрів. Знаки в усіх трьох системах лише чорнильні й кремові, тож під іншим зором змінюються тільки кольори HUD і мапи.', cvdBody),
    section('choice', 'Питання 1. Ваш вибір системи', 'Одна система, суміш або нотатка, що змінити. Відповідь зберігається тут, якщо сторінка відкрита зі сховищем.', pick),
    section('binding', 'Питання 2. Точка доставки', `Пакунків 10, а кімнат доставки 4–6, тож кімната отримує 2–3 пакунки. Знак називає кімнату, а не окреме місце, тож нинішнє правило «кожен пакунок — своє коло» лишитися не може. Це зміна правила для ${issue(255)} (core/); тут лише вибір. Малюнки — план кімнати згори в стилі Toy, однаковий для будь-якої системи знаків.`, bindBody),
    section('agent', 'Вирішив агент', 'Дрібні технічні рішення, які агент ухвалив сам. Кожне можна скасувати.', agentBody),
  ];
  const toc = [['systems', 'Коротко'], ['set', 'Набір'], ['carry', 'Пакунок'], ['doors', 'Двері'], ['map', 'Мапа'], ['spot', 'Доставка'], ['legibility', 'Читабельність'], ['vision', 'Дальтонізм'], ['choice', 'Питання 1'], ['binding', 'Питання 2'], ['agent', 'Вирішив агент']];

  // ----- HTML -----
  const symbols = [...SYM.values()].map((s) => `<symbol id="${s.id}" viewBox="0 0 ${s.w} ${s.h}">${s.body}</symbol>`).join('\n');
  const data = JSON.stringify({
    options: Object.fromEntries(SIDS.map((sid) => [sid, `${sid.toUpperCase()} · ${S[sid].name}`])),
    rooms: Object.fromEntries(ROOMS.map((r) => [r, roomName(r)])),
    bindings: Object.fromEntries(BINDINGS.map((b, i) => [b, `${'аб'[i]} · ${BIND_COPY[b].title}`])),
  }).replace(/</g, '\\u003c');
  const style = (id, text) => `<style id="${id}">\n${text.replace(/\s+$/, '')}\n</style>`;
  const roomSeg = '<div class="rs-seg" role="group" aria-label="кімната пакунка">'
    + delivery.map((r) => `<button type="button" data-room="${r}" aria-pressed="${r === DEFAULT_ROOM ? 'true' : 'false'}">${esc(SHORT[r])}</button>`).join('') + '</div>';
  const html = [
    '<!doctype html>',
    '<html lang="uk" data-text-size="default">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>Знаки кімнат</title>',
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    `<link rel="stylesheet" href="${FONT_LINK}">`,
    style('toy-tokens', tokensCss),
    style('rs-ui', uiCss),
    style('sc-page', readText('pages/components/page.css')),
    style('rs-world', worldCss),
    style('rs-cvd', cvdCss),
    style('rs-page', readText('pages/room-signs/page.css')),
    '</head>',
    '<body>',
    `<svg class="rs-defs" aria-hidden="true" focusable="false">\n${symbols}\n</svg>`,
    '<main>',
    '<h1>Знаки кімнат: три системи</h1>',
    '<p class="sc-lead">Пакунки без кольору: на кожному лише знак кімнати, куди його нести. Той самий знак стоїть на мапі, біля дверей і на місці доставки. Тут три системи таких знаків у грі, поруч одна з одною. Оберіть одну, змішайте або напишіть, що змінити; друге питання внизу — скільки точок доставки в кімнаті.</p>',
    '<p class="rs-rule">Жодна система не показує дорогу: знаки нерухомі, не світяться й не змінюються, коли несеш пакунок. Гравець сам зіставляє знак на коробці зі знаком на дверях і на мапі.</p>',
    `<ul class="rs-toc">${toc.map(([id, l]) => `<li><a href="#${id}">${esc(l)}</a></li>`).join('')}</ul>`,
    `<div class="rs-bar"><div class="rs-bar-row"><span class="rs-bar-label">Пакунок до:</span>${roomSeg}</div>`
      + '<div class="rs-bar-row"><span class="rs-bar-label">Кадри:</span><div class="rs-seg" role="group" aria-label="розмір кадрів">'
      + '<button type="button" data-zoom="1" aria-pressed="true">звичайні</button><button type="button" data-zoom="2" aria-pressed="false">великі, по одному</button></div></div>'
      + '<p class="rs-db" id="rs-db" data-state="wait">Перевіряю, чи можна тут зберегти відповідь…</p></div>',
    sections.join('\n'),
    `<footer class="rs-foot">Зібрано з токенів ${esc(sys.version)} і систем pages/room-signs/systems/a, b, c. Усі знаки — власні малюнки (own work, LICENCES.json кожної системи). `
      + 'Світ — сірі заглушки, не вигляд гри. Відстані й розміри — для екрана 1080p, 704 px на метр з 1 м, як у дослідженні (ground.md, розділ 3). Колірний зір — tools/a11y/cvd.js; контраст — формула WCAG (tools/lib/wcag.js).</footer>',
    '</main>',
    `<script id="rs-data" type="application/json">${data}</script>`,
    `<script>\n${readText('pages/room-signs/room-signs.js').replace(/\s+$/, '')}\n</script>`,
    '</body>',
    '</html>',
    '',
  ].join('\n');
  return [[OUT_UI, uiCss], [OUT_CVD, cvdCss], [OUT_HTML, html]];
}

function main(argv) {
  const check = argv.includes('--check');
  const unknown = argv.filter((a) => a !== '--check');
  if (unknown.length) {
    console.error(`unknown argument ${unknown[0]}\nusage: node pages/room-signs/build.js [--check]`);
    return 2;
  }
  let outputs;
  try {
    outputs = build();
  } catch (e) {
    if (e instanceof BuildError || /^emit-css:|^tokens:/.test(e.message)) { console.error(`error: ${e.message}`); return 1; }
    throw e;
  }
  for (const [file, text] of outputs) if (/\r/.test(text)) { console.error(`error: ${file} would contain CR bytes`); return 1; }
  if (check) {
    const stale = [];
    for (const [file, text] of outputs) {
      let disk = null;
      try { disk = fs.readFileSync(path.join(ROOT, file), 'utf8'); } catch (e) { disk = null; }
      if (disk !== text) stale.push(`${file} (${disk === null ? 'missing' : 'differs'})`);
    }
    if (stale.length) {
      console.log(`stale: ${stale.join(', ')}; run node pages/room-signs/build.js`);
      return 1;
    }
    console.log(`up to date: ${outputs.map(([f]) => f).join(', ')}`);
    return 0;
  }
  for (const [file, text] of outputs) fs.writeFileSync(path.join(ROOT, file), text);
  const kb = (t) => `${Math.round(Buffer.byteLength(t) / 1024)} KB`;
  console.log(`wrote ${outputs.map(([f, t]) => `${f} (${kb(t)})`).join(', ')}`);
  return 0;
}

module.exports = { main };

if (require.main === module) process.exitCode = main(process.argv.slice(2));
