// The CSS emitter (spec §8): dist/css/toy-tokens.css. Every authored token in source order on :root, aliases as var()
// chains, lengths as unitless ints (used as calc(var(--toy-…) * var(--px))), composites as their sub-value variables,
// the derived ramp stops after their ramp.steps token, then one block per non-default modifier context.
// Node 20, no packages.
'use strict';

const R = require('./resolve.js');
const { resultFor } = require('./emit-pack.js');

const HEADER = '/* Generated by tools/tokens/build.js from tokens/prime.resolver.json. Do not edit. */';
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const num = (x) => String(x);

function literalCss(type, raw) {
  switch (type) {
    case 'color': {
      const a = 'alpha' in raw ? raw.alpha : 1;
      if (a < 1) {
        const b = [1, 3, 5].map((i) => parseInt(raw.hex.slice(i, i + 2), 16));
        return `rgba(${b.join(', ')}, ${num(a)})`;
      }
      return raw.hex.toLowerCase();
    }
    case 'dimension': return num(raw.value);
    case 'duration': return `${raw.value}ms`;
    case 'cubicBezier': return `cubic-bezier(${raw.map(num).join(', ')})`;
    case 'number': case 'fontWeight': return num(raw);
    case 'fontFamily': return `"${String(raw).replace(/["\\]/g, '\\$&')}"`;
    default: return null;
  }
}

function decls(p, node, type) {
  const name = R.cssVar(p);
  if (R.COMPOSITES[type]) {
    return R.COMPOSITES[type].map(([key, subType, suffix]) => {
      let value;
      if (node.alias) value = `var(${R.cssVar(node.alias)}-${suffix})`;
      else {
        const raw = node.raw[key];
        value = R.isAlias(raw) ? `var(${R.cssVar(R.aliasPath(raw))})` : literalCss(subType, raw);
      }
      return `  ${name}-${suffix}: ${value};`;
    });
  }
  if (node.alias) return [`  ${name}: var(${R.cssVar(node.alias)});`];
  return [`  ${name}: ${literalCss(type, node.raw)};`];
}

function renderCss(model, results) {
  const r0 = results[0];
  const stopsAfter = new Map();
  for (const v of r0.variants) if (v.stops.length && v.ramp && v.ramp.steps) stopsAfter.set(v.ramp.steps.source, v.stops);
  const lines = [HEADER, ':root {'];
  for (const [p, n] of r0.res.tokens) {
    lines.push(...decls(p, n, r0.res.typeOf(p)));
    if (stopsAfter.has(p)) for (const s of stopsAfter.get(p)) lines.push(`  ${R.cssVar(s.path)}: ${s.hex};`);
  }
  lines.push('}');
  for (const m of model.modifiers) {
    for (const ctx of m.contexts) {
      if (ctx === m.default) continue;
      const r = resultFor(model, results, m.name, ctx);
      if (!r) continue;
      const files = m.files[ctx] || [];
      const block = [];
      for (const [p, n] of r.res.tokens) {
        if (!files.includes(n.file)) continue;
        if (R.packEqual(r.res.valueOf(p), r0.res.valueOf(p))) continue;
        block.push(...decls(p, n, r.res.typeOf(p)));
      }
      if (!block.length) continue;
      const attr = `data-${kebab(m.name)}`;
      lines.push(`:root[${attr}="${ctx}"] {`, ...block, '}');
      if (m.name.toLowerCase() === 'motion' && ctx === 'reduced') {
        lines.push('@media (prefers-reduced-motion: reduce) {', `  :root:not([${attr}="${m.default}"]) {`, ...block.map((d) => `  ${d}`), '  }', '}');
      }
    }
  }
  return lines.join('\n') + '\n';
}

module.exports = { renderCss, literalCss, HEADER };
