// The look-choices page (prime-game#150): ten open look questions, each option a DTCG overlay on tokens/ that goes
// through the real token tools (tools/tokens/api.js: resolve, validate, expand), the showcase's StyleBox-to-CSS
// emitter (pages/components/emit-css.js) and the contrast gates (tools/contrast/gates.js).
//
//   node pages/choices/build.js          write choices-tokens.css, choices.css and choices.html
//   node pages/choices/build.js --check  fail when any of them is stale
//
// choices.css (lint profile "generated") holds the components CSS of every variation the page shows, then one block
// per option scoped by .opt-<q>-<o>: the option's own emitted rules for each variation whose drawing differs from the
// base tokens. A token value the option changes is read from --toy-choice-<q>-<o>-<name> in choices-tokens.css (lint
// profile "tokens"), because generated CSS may not declare --toy-* variables.
// A question's reference card (what the tokens held before) may name its own overlay, <q>-ref. Once the engineer has
// chosen, options.json records it ("decided" per question, the date at the top); the page shows it from there, not
// from the page's store.
// Node 20, no packages.
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

const HERE = __dirname;
const ROOT = path.resolve(HERE, '..', '..');
const api = require(path.join(ROOT, 'tools', 'tokens', 'api.js'));
const { emitComponentsCss } = require(path.join(ROOT, 'pages', 'components', 'emit-css.js'));
const gatesLib = require(path.join(ROOT, 'tools', 'contrast', 'gates.js'));

const OUT_TOKENS = 'pages/choices/choices-tokens.css';
const OUT_CSS = 'pages/choices/choices.css';
const OUT_HTML = 'pages/choices/choices.html';
const FONT_LINK = 'https://fonts.googleapis.com/css2?family=Comfortaa:wght@300..700&display=swap';
const HEADER = '/* Generated by pages/choices/build.js from tools/tokens/api.js and pages/choices/overlays. Do not edit. */';

class BuildError extends Error {}
const fail = (msg) => { throw new BuildError(msg); };
const readText = (r) => fs.readFileSync(path.join(ROOT, r), 'utf8').replace(/\r\n/g, '\n');
const readJson = (r) => JSON.parse(readText(r));
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const num = (x) => String(x).replace('.', ',');
const MONTHS = ['січня', 'лютого', 'березня', 'квітня', 'травня', 'червня', 'липня', 'серпня', 'вересня', 'жовтня', 'листопада', 'грудня'];
const dateUk = (d) => { const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(d); if (!m) throw new Error(`options.json: decided.date ${d} is not YYYY-MM-DD`); return `${Number(m[3])} ${MONTHS[Number(m[2]) - 1]} ${m[1]}`; };
// Ukrainian plural of «пара»: 1, 21 пара; 2-4, 22-24 пари; 5-20, 25 пар.
const pairs = (n) => (n % 10 === 1 && n % 100 !== 11 ? 'пара' : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14) ? 'пари' : 'пар');

// ---------------------------------------------------------------------------------------------------------------
// CSS plumbing

// The custom properties of a tokens CSS (dist/css/toy-tokens.css form), resolved to literals for one text size.
function tokenVars(css, textSize) {
  const blocks = new Map();
  let sel = null;
  for (const line of css.split('\n')) {
    const open = /^\s*(\S[^{]*?)\s*\{\s*$/.exec(line);
    if (open) { sel = open[1]; if (!blocks.has(sel)) blocks.set(sel, new Map()); continue; }
    const d = /^\s*(--[\w-]+):\s*(.+);\s*$/.exec(line);
    if (d && sel) blocks.get(sel).set(d[1], d[2]);
  }
  const layers = [blocks.get(':root') || new Map()];
  if (textSize === 'large') layers.unshift(blocks.get(':root[data-text-size="large"]') || new Map());
  const raw = (n) => { for (const l of layers) if (l.has(n)) return l.get(n); return undefined; };
  const out = new Map();
  const names = new Set(layers.flatMap((l) => [...l.keys()]));
  for (const n of names) {
    let v = raw(n);
    for (let i = 0; i < 20; i++) {
      const m = /^var\((--[\w-]+)\)$/.exec(v || '');
      if (!m) break;
      v = raw(m[1]);
    }
    if (v === undefined) fail(`tokens CSS: ${n} does not resolve`);
    out.set(n, v);
  }
  return out;
}

// The components CSS split per variation: Map name -> { head, rules: [{ sel, decls: [[prop, value]] }] }.
function splitBlocks(css) {
  const blocks = new Map();
  let cur = null;
  let rule = null;
  for (const line of css.split('\n')) {
    let m;
    if ((m = /^\/\* (Toy[A-Za-z]+): /.exec(line))) { cur = { name: m[1], head: line, rules: [] }; blocks.set(m[1], cur); rule = null; continue; }
    if (!cur) continue;
    if ((m = /^(\S.*) \{$/.exec(line))) { rule = { sel: m[1], decls: [] }; cur.rules.push(rule); continue; }
    if (line === '}') { rule = null; continue; }
    if (rule && (m = /^ {2}([-\w]+): (.+);$/.exec(line))) rule.decls.push([m[1], m[2]]);
    else if (line.trim()) fail(`components CSS: unexpected line ${JSON.stringify(line)}`);
  }
  for (const b of blocks.values()) b.key = b.rules.map((r) => `${r.sel}{${r.decls.map((d) => d.join(':')).join(';')}}`).join('\n');
  return blocks;
}

const ruleText = (sel, decls) => [`${sel} {`, ...decls.map(([p, v]) => `  ${p}: ${v};`), '}'].join('\n');
const varRefs = (text) => [...text.matchAll(/var\((--toy-[\w-]+)\)/g)].map((m) => m[1]);
// The element a rule draws: its selector without state classes, the wide flag, data attributes and the context.
const subjectOf = (sel) => sel.split(', ')[0].replace(/^\[data-context="[a-z]+"\] /, '').replace(/\.is-[a-z]+|:focus-visible|\.tv-wide|\[data-[a-z-]+="[^"]*"\]/g, '');
const RESET = { 'box-shadow': 'none', opacity: '1', transform: 'none', 'text-shadow': 'none', '--tv-offset': '0' };
const resetOf = (prop) => (prop in RESET ? RESET[prop] : /^(margin|padding)-|^border-[a-z]+-width$/.test(prop) ? '0' : null);

// One option's block for one variation, as small as the cascade allows. A property of an element is "touched" when
// any of the option's rules for that element sets it differently from the base (another text, a changed token, or a
// base rule that no longer sets it). For every touched property, every option rule of that element that sets it is
// written under the scope, in the emitter's order, so the states keep their precedence; a base rule the option no
// longer has gets the value of the option's own rule underneath (or the CSS reset), so it stops counting.
function scopedBlock(scope, blockO, blockB, isChanged, rename) {
  const O = blockO.rules;
  const B = blockB ? blockB.rules : [];
  const bMap = new Map(B.map((r) => [r.sel, new Map(r.decls)]));
  const oMap = new Map(O.map((r) => [r.sel, new Map(r.decls)]));
  const key = (sel, p) => `${subjectOf(sel)} | ${p}`;
  const touched = new Set();
  for (const r of O) for (const [p, v] of r.decls) if ((bMap.get(r.sel) || new Map()).get(p) !== v || isChanged(v)) touched.add(key(r.sel, p));
  for (const r of B) for (const [p] of r.decls) if (!(oMap.get(r.sel) || new Map()).has(p)) touched.add(key(r.sel, p));
  // A base drawn as box-shadow sits under an opaque face (lint L13): the face's background comes along.
  for (const r of O) for (const [p, v] of r.decls) if (p === 'box-shadow' && v !== 'none' && touched.has(key(r.sel, p))) touched.add(key(r.sel, 'background'));
  const rules = O.map((r) => ({ sel: r.sel, decls: r.decls.filter(([p]) => touched.has(key(r.sel, p))) }));
  for (const r of B) {
    const own = oMap.get(r.sel) || new Map();
    const missing = r.decls.map(([p]) => p).filter((p) => !own.has(p));
    if (!missing.length) continue;
    let ro = rules.find((x) => x.sel === r.sel);
    if (!ro) {
      ro = { sel: r.sel, decls: [] };
      const at = rules.findIndex((x) => x.sel === subjectOf(r.sel));
      rules.splice(at + 1, 0, ro);
    }
    const under = r.sel === subjectOf(r.sel) ? null : oMap.get(subjectOf(r.sel));
    for (const p of missing) {
      const v = under && under.has(p) ? under.get(p) : resetOf(p);
      if (v === null) fail(`${blockO.name}: no reset for ${p} (${r.sel}) in ${scope}`);
      ro.decls.push([p, v]);
    }
  }
  const out = [blockO.head.replace('/* ', `/* ${scope} · `)];
  for (const r of rules) {
    if (!r.decls.length) continue;
    const sel = r.sel.split(', ').map((x) => `${scope} ${x}`).join(', ');
    out.push(ruleText(sel, r.decls.map(([p, v]) => [p, rename(v)])));
  }
  return out.length > 1 ? out.join('\n') : null;
}

// ---------------------------------------------------------------------------------------------------------------
// The page

function build() {
  const opts = readJson('pages/choices/options.json');
  const strings = readJson('pages/components/strings.json');
  const gatesJson = readJson('tokens/gates.json');
  const samples = Object.assign({}, strings.samples, opts.samples);
  const icons = { item: readText('pages/components/icons/item.svg').replace(/^<!--[^>]*-->\s*/, '').trim() };

  const base = api.load({ root: ROOT });
  const byName = new Map(base.variants.map((v) => [v.variation, v]));
  const baseVars = tokenVars(base.css, 'default');

  // Every option: its token system, gates and the drawing it changes.
  const keyOf = (q, o) => `${q.id}-${o.id}`;
  const options = [];
  for (const q of opts.questions) {
    if (!/^q\d+$/.test(q.id)) fail(`options.json: question id ${q.id}`);
    if (!q.options || q.options.length < 2 || q.options.length > 4) fail(`options.json: ${q.id} has ${q.options && q.options.length} options; 2 to 4`);
    q.options.forEach((o, i) => { if (o.id !== 'abcd'[i]) fail(`options.json: ${q.id} option ${i + 1} is ${o.id}, not ${'abcd'[i]}`); });
    if (q.options.filter((o) => o.recommended).length !== 1) fail(`options.json: ${q.id} needs exactly one recommended option`);
    if (q.decided !== undefined && !q.options.some((o) => o.id === q.decided)) fail(`options.json: ${q.id} is decided as ${q.decided}, which is not an option`);
    if (q.decided !== undefined && !(opts.decided && opts.decided.date)) fail(`options.json: ${q.id} is decided, but the page has no decided.date`);
    for (const o of q.options) {
      const key = keyOf(q, o);
      let sys = base;
      if (o.overlay) {
        if (o.overlay !== key) fail(`options.json: ${key} names the overlay ${o.overlay}`);
        try {
          sys = api.load({ root: ROOT, overlay: `pages/choices/overlays/${key}.tokens.json`, allow: o.allow || [] });
        } catch (e) {
          fail(`${key}: ${e.message}`);
        }
        const allowed = sys.warnings.filter((w) => w.allowed).map((w) => w.rule);
        for (const r of o.allow || []) if (!allowed.includes(r)) fail(`${key}: allows ${r}, but the overlay does not break it`);
      } else if (o.allow) fail(`${key}: allow without an overlay`);
      const mode = o.mode || 'default';
      options.push({ q, o, key, sys, mode });
    }
    if (q.reference) {
      const key = `${q.id}-ref`;
      let sys = base;
      if (q.reference.overlay) {
        if (q.reference.overlay !== key) fail(`options.json: the reference of ${q.id} names the overlay ${q.reference.overlay}`);
        try {
          sys = api.load({ root: ROOT, overlay: `pages/choices/overlays/${key}.tokens.json` });
        } catch (e) {
          fail(`${key}: ${e.message}`);
        }
      }
      options.push({ q, o: null, key, sys, mode: 'default', ref: true });
    }
  }
  const files = fs.readdirSync(path.join(HERE, 'overlays')).filter((f) => f.endsWith('.tokens.json')).map((f) => f.replace('.tokens.json', ''));
  for (const f of files) if (!options.some((x) => (x.o ? x.o.overlay : x.q.reference.overlay) === f)) fail(`overlays/${f}.tokens.json is not used by options.json`);

  // Gates per option (spec §11): the option's permutation; a stale waiver means the option fixes the waived pair.
  const DEF = 'textSize=default,motion=default';
  const defRows = (res) => new Map(res.results.filter((r) => r.permutation === DEF).map((r) => [r.id, r]));
  const baseDef = defRows(gatesLib.compute(base.pack, gatesJson));
  for (const x of options) {
    const res = gatesLib.compute(x.sys.pack, gatesJson);
    const perm = `textSize=${x.mode},motion=default`;
    x.rows = res.results.filter((r) => r.permutation === perm);
    if (!x.rows.length) fail(`${x.key}: the gates have no permutation ${perm}`);
    const other = res.errors.filter((e) => !/^stale waiver/.test(e));
    if (other.length) fail(`${x.key}: gates: ${other.join('; ')}`);
    x.fixesWaiver = res.errors.length > other.length;
    x.fails = x.rows.filter((r) => r.verdict === 'FAIL');
    x.def = defRows(res);
    x.ended = x.fixesWaiver ? [...baseDef.values()].filter((r) => r.verdict === 'WAIVED' && x.def.get(r.id) && x.def.get(r.id).verdict !== 'WAIVED').map((r) => r.id) : [];
    x.clashes = [];
  }

  // Options of different questions are chosen one by one, so they must combine. No two overlays may set the same
  // token; and an option that ends a waiver must keep it ended next to every other overlay that moves the waived pair
  // (the pair is computed on the two overlays merged; a clash is shown on both cards).
  const leaves = (node, pre, out) => {
    for (const [k, v] of Object.entries(node)) {
      if (k.startsWith('$') || !v || typeof v !== 'object') continue;
      if ('$value' in v) out.add(pre + k); else leaves(v, `${pre}${k}.`, out);
    }
    return out;
  };
  const merge = (a, b) => {
    for (const [k, v] of Object.entries(b)) {
      if (v && typeof v === 'object' && !('$value' in v) && a[k] && typeof a[k] === 'object') merge(a[k], v); else a[k] = v;
    }
    return a;
  };
  const withOv = options.filter((x) => x.o && x.o.overlay);
  for (const x of withOv) x.json = readJson(`pages/choices/overlays/${x.key}.tokens.json`);
  for (const x of withOv) x.paths = leaves(x.json, '', new Set());
  for (const x of withOv) for (const y of withOv) {
    if (x.q === y.q || x.key >= y.key) continue;
    const both = [...x.paths].filter((p) => y.paths.has(p));
    if (both.length) fail(`${x.key} and ${y.key} both set ${both.join(', ')}: options of different questions must combine`);
  }
  for (const x of withOv.filter((o) => o.ended.length)) {
    for (const y of withOv) {
      if (y.q === x.q || !x.ended.some((id) => y.def.get(id) && y.def.get(id).ratio !== baseDef.get(id).ratio)) continue;
      const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'choices-pair-'));
      let res;
      try {
        const file = path.join(tmp, `${x.key}+${y.key}.tokens.json`);
        fs.writeFileSync(file, JSON.stringify(merge(merge({}, JSON.parse(JSON.stringify(x.json))), y.json)));
        const sys = api.load({ root: ROOT, overlay: file, allow: [...(x.o.allow || []), ...(y.o.allow || [])] });
        res = defRows(gatesLib.compute(sys.pack, gatesJson));
      } catch (e) {
        fail(`${x.key} with ${y.key}: ${e.message}`);
      } finally {
        fs.rmSync(tmp, { recursive: true, force: true });
      }
      const bad = x.ended.map((id) => res.get(id)).filter((r) => r && (r.verdict === 'FAIL' || r.verdict === 'WAIVED'));
      // The auto row of the same pair repeats a named gate: show the named one.
      const named = bad.filter((r) => !r.id.startsWith('auto:'));
      const shown = named.length ? named : bad;
      if (shown.length) { x.clashes.push({ y, bad: shown }); y.clashes.push({ y: x, bad: shown }); }
    }
  }

  // ----- samples -----
  const used = new Set();
  const usedSamples = new Set();
  let cardUsed = new Set();
  const V = (name) => { if (!byName.has(name)) fail(`unknown variation ${name}`); used.add(name); cardUsed.add(name); return name; };
  const S = (key, cls, extra) => {
    if (!samples[key]) fail(`unknown sample text ${key}`);
    usedSamples.add(key);
    return `<span${cls ? ` class="${cls}"` : ''}${extra || ''} data-s="${key}">${esc(samples[key].uk)}</span>`;
  };
  const btn = (name, label, o = {}) => {
    V(name);
    const cls = [`tv-${name}`];
    if (o.force) cls.push(`is-${o.force}`);
    const a = ['type="button"', `class="${cls.join(' ')}"`, 'data-live'];
    if (o.force) a.push(`data-force="${o.force}"`);
    if (o.toggle) { o.toggle.forEach(V); a.push(`data-toggle="${o.toggle.join(' ')}"`, `aria-pressed="${o.pressed ? 'true' : 'false'}"`); }
    if (o.group) a.push(`data-group="${o.group}"`);
    return `<button ${a.join(' ')}>${o.content || S(label)}<span class="tv-focus"></span></button>`;
  };
  const box = (name, inner, cls) => `<div class="tv-${V(name)}${cls ? ` ${cls}` : ''}">${inner}</div>`;
  const stage = (ctx, label, html, tile) => `<p class="ch-stage-label">${esc(label)}</p>`
    + `<div class="ch-stage${tile ? ` sc-tile-${tile}` : ''}" data-context="${ctx}"><div class="sc-sample"${/class="[^"]*ch-full/.test(html.slice(0, 200)) ? ' style="--pad: 0"' : ''}>${html}</div></div>`;
  const group = (html) => `<div class="ch-row">${html}</div>`;
  const icon = () => `<span class="sc-icon">${icons.item}</span>`;
  const bar = (name, value) => `<div class="tv-${V('ToyBarTrack')} sc-barbox"><div class="tv-${V(name)}" style="--value: ${value}"${byName.get(name).stops && byName.get(name).stops.length ? ` data-step="${String(Math.floor(value * (byName.get(name).stops.length - 1) + 0.5)).padStart(2, '0')}"` : ''}><i class="tv-fill"></i></div></div>`;
  const hud = () => `<div class="sc-hudbar">${box('ToyBarLabel', S('stamina', `tv-${V('ToyHudCaption')}`))}${bar('ToyBarStamina', 0.9)}`
    + `${box('ToyBarLabel', S('health', 'tv-ToyHudCaption'))}${bar('ToyBarHealth', 0.8)}</div>`
    + group(`${box('ToySlotActive', `${icon()}${S('knife', `tv-${V('ToySlotText')}`)}`)}${box('ToySlot', S('belt', `tv-${V('ToySlotTextEmpty')}`))}`);
  const escPanel = (extra) => box('ToyPanelMenu', `${S('settings', `tv-${V('ToyTitleOnLight')}`)}`
    + group(`${btn('ToyTabSelected', 'game')}${btn('ToyTab', 'lobby')}${btn('ToyTab', 'character')}`)
    + box('ToySettingRow', `${S('game_volume', `tv-${V('ToySettingRowText')}`)}${S('volume_value', `tv-${V('ToySettingRowValue')}`)}`, 'sc-setrow')
    + box('ToySettingRow', `${S('match_duration', 'tv-ToySettingRowText')}<span class="sc-stepper">${btn('ToyStepper', 'minus', extra ? { force: 'disabled' } : {})}`
      + `${S('min10', 'tv-ToySettingRowValue')}${btn('ToyStepper', 'plus', extra ? { force: 'disabled' } : {})}</span>`, 'sc-setrow')
    + (extra ? `<div class="ch-row">${box('ToyKeyRoundQuiet', S('question', `tv-${V('ToyKeyQuietText')}`))}${S('host_only', `tv-${V('ToyTextMutedOnLight')} sc-wrap`)}</div>` : '')
    + `<div class="sc-actions">${btn('ToyButtonPrimary', 'resume')}${btn('ToyButtonGhostOnLight', 'leave')}</div>`, 'sc-panel ch-panel');
  V('ToyBasePanel');
  const keyRow = (keyVar, textVar, list) => list.map(([k, cap, wide]) => `<span class="ch-key">${box(keyVar, S(k, `tv-${V('ToyKeyText')}`), wide ? 'tv-wide' : '')}${S(cap, `tv-${V(textVar)}`)}</span>`).join('');
  const KEYS = [['space', 'jump', true], ['shift', 'run', true], ['tab_key', 'map_word', true], ['esc', 'menu_word', true], ['key_e', 'take', false]];

  const swatch = (sys, name) => {
    const t = sys.tokens.get(`palette.${name}`);
    const a = t.rgba && t.rgba[3] !== 1 ? ` · ${Math.round(t.rgba[3] * 100)} %` : '';
    return `<span class="ch-sw"><i style="background: ${t.hex}"></i><b>${esc(name)}</b><code>${esc(t.hex)}${a}</code></span>`;
  };

  const SAMPLES = {
    disabled: () => stage('dark', 'на темному', group(`${btn('ToyButtonPrimary', 'play', { force: 'disabled' })}${btn('ToyButtonSecondary', 'settings', { force: 'disabled' })}${btn('ToyButtonGhostOnDark', 'quit', { force: 'disabled' })}`))
      + stage('light', 'на кремовій панелі', group(`${btn('ToyButtonPrimary', 'resume', { force: 'disabled' })}${btn('ToyButtonSecondary', 'settings', { force: 'disabled' })}${btn('ToyButtonGhostOnLight', 'cancel', { force: 'disabled' })}`)),
    focus: () => stage('dark', 'на темному', group(`${btn('ToyButtonPrimary', 'play', { force: 'focus' })}${btn('ToyButtonGhostOnDark', 'quit', { force: 'focus' })}${btn('ToyChipToggleOnDark', 'same_net', { force: 'focus' })}`))
      + stage('light', 'на кремовій панелі', group(`${btn('ToyButtonSecondary', 'settings', { force: 'focus' })}${btn('ToyTabSelected', 'game', { force: 'focus' })}${btn('ToyTab', 'lobby', { force: 'focus' })}`
        + `<div class="tv-${V('ToyField')} is-focus" data-force="focus">${S('name_olena')}<span class="tv-focus"></span></div>`)),
    hover: () => stage('dark', 'на темному', group(`${btn('ToyButtonGhostOnDark', 'skip', { force: 'hover' })}${btn('ToyChipToggleOnDark', 'later', { force: 'hover' })}`))
      + stage('light', 'на кремовій панелі', group(`${btn('ToyTabSelected', 'game')}${btn('ToyTab', 'lobby', { force: 'hover' })}${btn('ToyButtonGhostOnLight', 'cancel', { force: 'hover' })}${btn('ToyChipToggleOnLight', 'same_net', { force: 'hover' })}`)),
    leave: (o) => stage('dark', 'діалог над сірим світом', box('ToyBackdrop', box('ToyPanelDialog',
      `${S('leave_q', `tv-${V('ToyTitleOnLight')} sc-wrap`)}${S('leave_body', `tv-${V('ToyTextOnLight')} sc-wrap`)}${S('host_note', `tv-${V('ToyTextMutedOnLight')} sc-wrap`)}`
      + `<div class="sc-actions">${btn(o.leave, 'leave')}${btn('ToyButtonGhostOnLight', 'cancel')}</div>`, 'sc-dialog ch-panel'), 'sc-backdrop ch-full'), 'grey'),
    large: () => stage('dark', 'меню Esc', escPanel(false)) + stage('dark', 'кут HUD над сірим світом', hud(), 'grey'),
    presets: (o, x) => {
      const g = `${x.key}`;
      const card = (i, label, note) => btn(i === 0 ? 'ToyPresetCardSelected' : 'ToyPresetCard', label, {
        toggle: ['ToyPresetCard', 'ToyPresetCardSelected'], pressed: i === 0, group: g,
        content: `<span class="sc-stack">${S(label)}${S(note, `tv-${V(i === 0 ? 'ToyPresetCardNoteSelected' : 'ToyPresetCardNote')}`, ' data-note="ToyPresetCardNote ToyPresetCardNoteSelected"')}</span>`,
      });
      V('ToyPresetCardNote'); V('ToyPresetCardNoteSelected'); V('ToyBaseCard');
      return stage('light', 'на кремовій панелі: торкніться картки', `<div class="ch-row ch-cards">${card(0, 'standard', 'min10')}${card(1, 'quick', 'min5')}${card(2, 'no_knives', 'knives0')}${btn('ToyPresetCardQuiet', 'save_own')}</div>`);
    },
    press: () => stage('dark', 'на темному: натисніть і тримайте', group(`${btn('ToyButtonPrimary', 'play')}${btn('ToyButtonSecondary', 'settings')}`))
      + stage('light', 'на кремовій панелі', group(`${btn('ToyButtonPrimary', 'resume')}${btn('ToyButtonSecondary', 'settings')}`)),
    backdrop: () => ['white', 'grey'].map((t) => stage('dark', t === 'white' ? 'затемнення над білою стіною' : 'затемнення над сірим світом', box('ToyBackdrop',
      `${S('name', `tv-${V('ToyTextMutedOnDark')}`)}${box('ToyField', S('name_olena'))}${S('version', 'tv-ToyTextMutedOnDark')}`, 'sc-backdrop ch-full ch-col'), t)).join(''),
    keys: () => stage('dark', 'підказка в HUD над сірим світом', box('ToyPlate', keyRow('ToyKeyOnDark', 'ToyPlateText', KEYS), 'ch-keys'), 'grey')
      + stage('light', 'на кремовій панелі', `<div class="ch-keys">${keyRow('ToyKeyOnLight', 'ToyTextOnLight', KEYS)}</div>`),
    palette: (o, x) => `<div class="ch-pal"><p>сливові</p>${['ink', 'night', 'backdrop', 'drop'].map((n) => swatch(x.sys, n)).join('')}`
      + `<p>бузкові</p>${['key-quiet', 'lavender', 'row-line', 'track-light'].map((n) => swatch(x.sys, n)).join('')}</div>`
      + stage('dark', 'меню над білою стіною', box('ToyBackdrop', escPanel(true), 'sc-backdrop ch-full'), 'white')
      + stage('dark', 'кут HUD над сірим світом', hud(), 'grey'),
  };

  // ----- facts that are not contrast, read from the option's tokens -----
  const px = (f) => (f && f.value && typeof f.value.px === 'number' ? f.value.px : null);
  const variantOf = (sys, name) => sys.variants.find((v) => v.variation === name);
  const FACTS = {
    large: (x) => {
      const keys = ['caption', 'small', 'body', 'body-large', 'heading', 'title'];
      const big = x.mode === 'large' ? x.sys.pack.modes.textSize.large : null;
      return [`розміри, px: ${keys.map((k) => { const b = base.tokens.get(`font.size.${k}`).px; return big ? `${b}→${big[`font.size.${k}`].px}` : String(b); }).join(' · ')}`];
    },
    presets: (x) => {
      const idle = variantOf(x.sys, 'ToyPresetCard').states.normal;
      const sel = variantOf(x.sys, 'ToyPresetCardSelected').states.normal;
      const grow = 2 * (px(sel['content-margin-top']) - px(idle['content-margin-top']));
      return [`відступ: звичайна ${px(idle['content-margin-top']) - px(idle['border-width-top'])} px, вибрана ${px(sel['content-margin-top']) - px(sel['border-width-top'])} px`,
        grow ? `вибрана більша на ${grow} px по ширині й висоті` : 'вибрана того ж розміру'];
    },
    press: (x) => ['ToyButtonPrimary', 'ToyButtonSecondary'].map((n) => {
      const v = variantOf(x.sys, n);
      return `${n === 'ToyButtonPrimary' ? 'жовта' : 'біла'}: опускається на ${px(v.press.held)} px з ${px(v.press.depth)}`;
    }),
    keys: (x) => {
      const v = variantOf(x.sys, 'ToyKeyOnDark');
      const w = px(v.size['wide-min-width']);
      return [w > px(v.size['min-width']) ? `широка клавіша: щонайменше ${w} px` : 'широка клавіша: за написом'];
    },
  };

  // ----- ratios -----
  const verdict = (r) => (r.verdict === 'FAIL' ? ['fail', '✗'] : r.verdict === 'WAIVED' ? ['waived', '✗'] : ['ok', '✓']);
  const describe = (r) => {
    const parts = r.id.split(':');
    if (parts[0] !== 'auto') return `${r.id}: ${r.fgPath} на ${r.bgPath}${r.over ? ` над ${r.over}` : ''}`;
    return `${parts[1]} · ${parts[2]}${parts[3] ? ` · ${parts.slice(3).join(':').replace(/color\.surface\./g, '')}` : ''}`;
  };
  const ratioList = (x) => {
    const spec = (x.o && x.o.ratios) || x.q.ratios || [];
    return spec.map((s) => {
      const re = new RegExp(s.match);
      const rows = x.rows.filter((r) => re.test(r.id) && r.min !== null);
      if (!rows.length) fail(`${x.key}: no gate row matches ${s.match}`);
      const worst = rows.reduce((a, b) => (b.ratio / b.min < a.ratio / a.min ? b : a));
      const [cls, mark] = verdict(worst);
      const tail = worst.verdict === 'WAIVED' ? ' · тимчасово дозволено' : '';
      return `<li class="ch-r-${cls}"><span>${esc(s.label)}</span> <b>${mark} ${num(worst.ratio.toFixed(2))}:1</b> <small>поріг ${num(worst.min)}${tail}</small></li>`;
    });
  };

  // ----- the option cards -----
  const BADGES = { dec: 'вирішено', rec: 'моя порада', cur: 'зараз у токенах', fail: 'не проходить контраст' };
  const badge = (kind, text) => `<span class="ch-badge ch-badge-${kind}">${esc(text || BADGES[kind])}</span>`;
  const card = (x) => {
    const sample = SAMPLES[x.q.sample];
    if (!sample) fail(`${x.q.id}: unknown sample ${x.q.sample}`);
    const o = x.o || {};
    cardUsed = new Set();
    const html = sample(o, x);
    x.used = cardUsed;
    const badges = [];
    const decided = !x.ref && x.q.decided === o.id;
    if (decided) badges.push(badge('dec'));
    if (o.recommended) badges.push(badge('rec'));
    if (o.current) badges.push(badge('cur'));
    if (x.fails.length) badges.push(badge('fail'));
    for (const r of o.allow || []) badges.push(badge('rule', `змінює правило ${r}`));
    const items = [];
    const facts = FACTS[x.q.sample] ? FACTS[x.q.sample](x) : [];
    for (const f of facts) items.push(`<li>${esc(f)}</li>`);
    items.push(...ratioList(x));
    if (x.fails.length) {
      const shown = x.fails.slice().sort((a, b) => a.ratio / a.min - b.ratio / b.min).slice(0, 3);
      items.push(`<li class="ch-r-fail"><span>не проходить: ${x.fails.length} ${pairs(x.fails.length)}, найгірші:</span></li>`);
      for (const r of shown) items.push(`<li class="ch-r-fail ch-r-sub"><span>${esc(describe(r))}</span> <b>✗ ${num(r.ratio.toFixed(2))}:1</b> <small>поріг ${num(r.min)}</small></li>`);
    } else if (!(x.o && x.o.ratios) && !x.q.ratios) items.push('<li class="ch-r-ok"><span>контраст: усі пороги проходять</span></li>');
    if (x.ended && x.ended.length) {
      const named = x.ended.filter((id) => !id.startsWith('auto:'));
      items.push(`<li class="ch-r-ok"><span>виняток ${esc((named.length ? named : x.ended).join(', '))} більше не потрібен</span></li>`);
    }
    for (const c of x.clashes || []) {
      for (const r of c.bad) items.push(`<li class="ch-r-fail"><span>разом із ${esc(c.y.q.id.slice(1) + c.y.o.id)}: ${esc(r.id)} знову не проходить</span> <b>✗ ${num(r.ratio.toFixed(2))}:1</b> <small>поріг ${num(r.min)}</small></li>`);
    }
    const head = x.ref
      ? `<div class="ch-opt-head"><span class="ch-letter">·</span><h3>${esc(x.q.reference.title)}</h3></div>`
      : `<div class="ch-opt-head"><span class="ch-letter">${o.id}</span><h3>${esc(o.title)}</h3></div>${badges.length ? `<div class="ch-badges">${badges.join('')}</div>` : ''}`
        + `<p class="ch-desc">${esc(o.desc)}</p>`;
    const take = x.ref ? '' : `<div class="ch-act"><button type="button" class="ch-btn ch-take" data-take="${o.id}">Беру цей</button><span class="ch-chosen">✓ ваш вибір</span></div>`;
    const scope = x.sys === base && x.mode === 'default' && x.ref ? '' : ` opt-${x.key}`;
    return `<article class="ch-opt${x.ref ? ' ch-ref' : ''}${decided ? ' is-decided' : ''}${scope}" data-o="${x.ref ? 'ref' : o.id}">${head}`
      + `<div class="ch-sample">${html}</div><ul class="ch-facts">${items.join('')}</ul>${take}</article>`;
  };

  const sections = opts.questions.map((q, i) => {
    const list = options.filter((x) => x.q === q);
    const ordered = list.filter((x) => x.ref).concat(list.filter((x) => !x.ref));
    const dec = q.options.find((o) => o.id === q.decided);
    const decTitle = dec ? (/^«.*»$/.test(dec.title) ? dec.title : `«${dec.title}»`) : '';
    const decidedLine = dec ? `<p class="ch-decided">вирішено ${esc(dateUk(opts.decided.date))}: ${dec.id} ${esc(decTitle)}</p>` : '';
    const force = q.force ? `<button type="button" class="ch-btn ch-force" data-force-toggle="${q.force.kind}" aria-pressed="${q.force.on ? 'true' : 'false'}">${esc(q.force.label)}</button>` : '';
    return `<section class="ch-q" id="${q.id}" data-q="${q.id}">`
      + `<div class="ch-q-head"><h2><span class="ch-num">${i + 1}</span>${esc(q.title)}</h2><p class="ch-ask">${esc(q.ask)}</p>`
      + decidedLine + `<div class="ch-q-tools">${force}<p class="ch-saved" data-saved>ще без відповіді</p></div></div>`
      + `<div class="ch-opts">${ordered.map(card).join('')}</div>`
      + `<div class="ch-note"><label for="note-${q.id}">Нотатка (не обовʼязково)</label><textarea id="note-${q.id}" rows="2" data-note-input></textarea>`
      + `<div class="ch-note-act"><button type="button" class="ch-btn" data-save-note>Зберегти нотатку</button>`
      + `<button type="button" class="ch-btn ch-btn-quiet" data-other>Жоден із цих: інше (у нотатці)</button></div></div></section>`;
  });

  // ----- CSS -----
  const baseBlocks = splitBlocks(emitComponentsCss(base));
  const css = [HEADER, '', '/* The base tokens: every variation the page shows. */'];
  for (const [name, b] of baseBlocks) {
    if (!used.has(name)) continue;
    css.push(b.head, ...b.rules.map((r) => ruleText(r.sel, r.decls)));
  }
  const tokenLines = [];
  for (const x of options) {
    if (x.sys === base && x.mode === 'default') continue;
    const vars = tokenVars(x.sys.css, x.mode);
    const changed = new Set([...vars].filter(([n, v]) => baseVars.get(n) !== v).map(([n]) => n));
    const blocks = x.sys === base ? baseBlocks : splitBlocks(emitComponentsCss(x.sys));
    const need = new Set();
    const rename = (v) => v.replace(/var\((--toy-[\w-]+)\)/g, (all, n) => {
      if (!changed.has(n)) return all;
      need.add(n);
      return `var(--toy-choice-${x.key}-${n.slice(6)})`;
    });
    const out = [];
    const isChanged = (v) => varRefs(v).some((n) => changed.has(n));
    for (const [name, b] of blocks) {
      if (!x.used.has(name)) continue;
      const bb = baseBlocks.get(name);
      if (bb && bb.key === b.key && !b.rules.some((r) => r.decls.some(([, v]) => isChanged(v)))) continue;
      const block = scopedBlock(`.opt-${x.key}`, b, bb, isChanged, rename);
      if (block) out.push(block);
    }
    if (!out.length && x.sys !== base) fail(`${x.key}: the overlay changes nothing the page shows`);
    if (out.length) css.push('', `/* ${x.key}: ${x.o ? x.o.title : x.q.reference.title} */`, ...out);
    for (const n of [...need].sort()) tokenLines.push(`  --toy-choice-${x.key}-${n.slice(6)}: ${vars.get(n)};`);
  }
  const tokensCss = [HEADER, ':root {', ...tokenLines, '}', ''].join('\n');
  const componentsCss = css.join('\n') + '\n';

  // ----- HTML -----
  const unused = Object.keys(opts.samples).filter((k) => !usedSamples.has(k));
  if (unused.length) fail(`options.json: unused samples: ${unused.join(', ')}`);
  const sampleJson = JSON.stringify(Object.fromEntries([...usedSamples].sort().map((k) => [k, { uk: samples[k].uk, en: samples[k].en }]))).replace(/</g, '\\u003c');
  const data = JSON.stringify({ questions: opts.questions.map((q) => ({ id: q.id, title: q.title, options: q.options.map((o) => ({ id: o.id, title: o.title })) })) }).replace(/</g, '\\u003c');
  const style = (id, text) => `<style id="${id}">\n${text.replace(/\s+$/, '')}\n</style>`;
  const n = opts.questions.length;
  const html = [
    '<!doctype html>',
    '<html lang="uk" data-text-size="default">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>Вибір вигляду</title>',
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    `<link rel="stylesheet" href="${FONT_LINK}">`,
    style('toy-tokens', readText('dist/css/toy-tokens.css')),
    style('choice-tokens', tokensCss),
    style('choice-components', componentsCss),
    style('sc-page', readText('pages/components/page.css')),
    style('ch-page', readText('pages/choices/page.css')),
    '</head>',
    '<body>',
    '<main>',
    `<h1>${esc(opts.title)}</h1>`,
    `<p class="sc-lead">${esc(opts.lead)}</p>`,
    opts.decided ? `<p class="ch-status">${esc(opts.decided.text)}</p>` : '',
    `<ul class="ch-how">${opts.how.map((h) => `<li>${esc(h)}</li>`).join('')}</ul>`,
    '<div class="sc-bar ch-bar" id="sc-bar"><div class="ch-bar-row">'
      + `<p class="ch-progress" aria-live="polite">відповіді: <b id="ch-count">0</b> з ${n}</p>`
      + '<div class="sc-ctl" role="group" aria-label="мова зразків"><div class="sc-seg"><button type="button" data-ctl="lang" data-val="uk" aria-pressed="true">UA</button>'
      + '<button type="button" data-ctl="lang" data-val="en" aria-pressed="false">EN</button></div></div></div>'
      + '<p class="ch-db" id="ch-db" data-state="wait">Перевіряю, чи можна тут зберегти відповіді…</p></div>',
    '<div class="ch-summary" id="ch-summary" hidden><label for="ch-summary-text">Підсумок, щоб скопіювати в чат</label><textarea id="ch-summary-text" rows="4" readonly></textarea></div>',
    sections.join('\n'),
    `<footer class="ch-foot">Зібрано з токенів ${esc(base.version)} і накладок pages/choices/overlays; контраст — tools/contrast/gates.js.</footer>`,
    '</main>',
    `<script id="sc-samples" type="application/json">${sampleJson}</script>`,
    `<script id="ch-data" type="application/json">${data}</script>`,
    `<script>\n${readText('pages/components/page.js').replace(/\s+$/, '')}\n</script>`,
    `<script>\n${readText('pages/choices/choices.js').replace(/\s+$/, '')}\n</script>`,
    '</body>',
    '</html>',
    '',
  ].join('\n');
  return [[OUT_TOKENS, tokensCss], [OUT_CSS, componentsCss], [OUT_HTML, html]];
}

function main(argv) {
  const check = argv.includes('--check');
  const unknown = argv.filter((a) => a !== '--check');
  if (unknown.length) {
    console.error(`unknown argument ${unknown[0]}\nusage: node pages/choices/build.js [--check]`);
    return 2;
  }
  let outputs;
  try {
    outputs = build();
  } catch (e) {
    if (e instanceof BuildError || /^emit-css:|^tokens:/.test(e.message)) { console.error(`error: ${e.message}`); return 1; }
    throw e;
  }
  for (const [file, text] of outputs) if (/\r/.test(text)) { console.error(`error: ${file} would contain CR bytes`); return 1; }
  if (check) {
    const stale = [];
    for (const [file, text] of outputs) {
      let disk = null;
      try { disk = fs.readFileSync(path.join(ROOT, file), 'utf8'); } catch (e) { disk = null; }
      if (disk !== text) stale.push(`${file} (${disk === null ? 'missing' : 'differs'})`);
    }
    if (stale.length) {
      console.log(`stale: ${stale.join(', ')}; run node pages/choices/build.js`);
      return 1;
    }
    console.log(`up to date: ${outputs.map(([f]) => f).join(', ')}`);
    return 0;
  }
  for (const [file, text] of outputs) fs.writeFileSync(path.join(ROOT, file), text);
  const kb = (t) => `${Math.round(Buffer.byteLength(t) / 1024)} KB`;
  console.log(`wrote ${outputs.map(([f, t]) => `${f} (${kb(t)})`).join(', ')}`);
  return 0;
}

module.exports = { main, tokenVars, splitBlocks };

if (require.main === module) process.exitCode = main(process.argv.slice(2));
