// The components CSS (spec §13): one .tv-<Variation> class per non-abstract variation, generated from the token system
// that tools/tokens/api.js loads. Every value is a var(--toy-…) of the field's source token; nothing is hand-written.
//   const { emitComponentsCss } = require('./emit-css.js');
//   const css = emitComponentsCss(require('../../tools/tokens/api.js').load({ root }));
// Node 20, no packages.
'use strict';

const HEADER = '/* Generated by pages/components/build.js from tools/tokens/api.js (spec §13). Do not edit. */';
const SIDES = ['top', 'right', 'bottom', 'left'];
const CORNERS = ['top-left', 'top-right', 'bottom-right', 'bottom-left'];
// Godot state -> CSS state class (§13.1). `normal` and `panel` are the base rule; `focus` is the .tv-focus child;
// `hover-pressed` is not drawn while a press is held (BaseButton draws `pressed` then), so it has no class here.
const STATE_CLASS = [['hover', 'is-hover'], ['pressed', 'is-held'], ['disabled', 'is-disabled'], ['read-only', 'is-readonly']];
// Theme items that have a CSS form: item -> [child class, property].
const ITEM_MAP = {
  'placeholder-color': ['tv-placeholder', 'color'],
  'caret-color': ['tv-caret', 'background'],
  'selection-color': ['tv-selection', 'background'],
  'selected-font-color': ['tv-selection', 'color'],
  'icon-on': ['tv-icon-on', 'color'],
  'icon-off': ['tv-icon-off', 'color'],
};
const LOGO_ITEMS = new Set(['shadow-offset-x', 'shadow-offset-y', 'shadow-outline-size']);
// A Button's icon colours (Godot's icon_*_color) tint the .tv-icon child per state; the order of the CSS rules is the
// order here, so hover, held and disabled beat focus (Button's focus colour replaces only the normal state's, spec §4.18).
// hover-pressed has no CSS state class (see STATE_CLASS), so icon-hover-pressed-color has no CSS form by design.
const ICON_STATE = [['icon-normal-color', null], ['icon-focus-color', 'is-focus'], ['icon-hover-color', 'is-hover'],
  ['icon-pressed-color', 'is-held'], ['icon-disabled-color', 'is-disabled']];
const NO_CSS_ITEMS = new Set(['icon-hover-pressed-color',
  // OptionButton's modulate_arrow = 1 tints the arrow with the label colour: in CSS the .tv-arrow child's currentColor.
  'modulate-arrow']);

function emitComponentsCss(sys) {
  const v = (p) => `var(${sys.cssVar(p)})`;
  const byName = new Map(sys.variants.map((x) => [x.variation, x]));
  const fail = (variant, msg) => { throw new Error(`emit-css: ${variant.variation} (${variant.prefix}): ${msg}`); };

  // A length field as CSS: calc(var(--toy-…) * var(--px)), or 0 for a completion default of 0.
  const term = (variant, f, what) => {
    if (f.source) return v(f.source);
    const px = f.value && f.value.px;
    if (px === 0 || px === undefined) return null;
    return fail(variant, `${what} has no source but the value ${px}`);
  };
  const len = (variant, f, what) => {
    const t = term(variant, f, what);
    return t ? `calc(${t} * var(--px))` : '0';
  };
  // calc((a + b - c - d) * var(--px)) with null terms dropped; plus/minus are lists of [field, what].
  const sum = (variant, plus, minus) => {
    const P = plus.map(([f, w]) => term(variant, f, w)).filter(Boolean);
    const M = minus.map(([f, w]) => term(variant, f, w)).filter(Boolean);
    if (!P.length && !M.length) return '0';
    if (P.length === 1 && !M.length) return `calc(${P[0]} * var(--px))`;
    const head = P.length ? P.join(' + ') : '0';
    return `calc((${[head, ...M].join(' - ')}) * var(--px))`;
  };
  const colour = (f) => (f && f.source ? v(f.source) : 'var(--toy-palette-clear)');
  const px = (f) => (f && f.value && typeof f.value.px === 'number' ? f.value.px : 0);

  // The drawing of one StyleBox record (§13.2), as an ordered Map prop -> value. Margins are always present ('0' when
  // the expand margin is 0) so that state rules can undo a base rule's margin.
  function boxDecls(variant, rec) {
    const d = new Map();
    d.set('box-sizing', 'border-box');
    d.set('position', 'relative');
    const center = rec['draw-center'] ? rec['draw-center'].value.value !== false : true;
    d.set('background', center ? colour(rec['bg-color']) : 'var(--toy-palette-clear)');
    d.set('border-style', 'solid');
    const widths = SIDES.map((s) => px(rec[`border-width-${s}`]));
    if (rec['border-color'].source) d.set('border-color', v(rec['border-color'].source));
    else if (widths.some((w) => w !== 0)) fail(variant, 'a border is drawn without a border colour');
    for (const s of SIDES) d.set(`border-${s}-width`, len(variant, rec[`border-width-${s}`], `border-width-${s}`));
    for (const c of CORNERS) d.set(`border-${c}-radius`, len(variant, rec[`corner-radius-${c}`], `corner-radius-${c}`));
    for (const s of SIDES) {
      const ex = rec[`expand-margin-${s}`];
      const plus = [[rec[`content-margin-${s}`], `content-margin-${s}`]];
      if (px(ex) !== 0) plus.push([ex, `expand-margin-${s}`]);
      d.set(`padding-${s}`, sum(variant, plus, [[rec[`border-width-${s}`], `border-width-${s}`]]));
    }
    for (const s of SIDES) {
      const ex = rec[`expand-margin-${s}`];
      d.set(`margin-${s}`, px(ex) !== 0 ? `calc(${term(variant, ex, `expand-margin-${s}`)} * -1 * var(--px))` : '0');
    }
    return d;
  }

  function fontDecls(label, fontColour) {
    const d = new Map();
    if (label && label.source) {
      const b = sys.cssVar(label.source);
      d.set('font-family', `var(${b}-font-family), system-ui, sans-serif`);
      d.set('font-size', `calc(var(${b}-font-size) * var(--px))`);
      d.set('font-weight', `var(${b}-font-weight)`);
      d.set('line-height', `var(${b}-line-height)`);
      d.set('letter-spacing', `calc(var(${b}-letter-spacing) * var(--px))`);
    }
    if (fontColour && fontColour.source) d.set('color', v(fontColour.source));
    return d;
  }

  // The inset of the focus ring from the padding box of a state's record (§13.2): ex_state − bw_state − ex_focus.
  function focusInsets(variant, rec, focus) {
    const d = new Map();
    for (const s of SIDES) {
      const ex = rec[`expand-margin-${s}`];
      const plus = px(ex) !== 0 ? [[ex, `expand-margin-${s}`]] : [];
      d.set(s, sum(variant, plus, [[rec[`border-width-${s}`], `border-width-${s}`], [focus[`expand-margin-${s}`], `focus expand-margin-${s}`]]));
    }
    return d;
  }

  const out = [HEADER, ''];
  const rule = (sel, decls) => {
    const list = decls instanceof Map ? [...decls].map(([p, x]) => `${p}: ${x};`) : decls;
    if (!list.length) return;
    out.push(`${sel} {`, ...list.map((x) => `  ${x}`), '}');
  };
  const diff = (base, next) => {
    const d = new Map();
    for (const [p, x] of next) if ((base.has(p) ? base.get(p) : '0') !== x) d.set(p, x);
    return d;
  };
  const motionOf = (variant) => {
    for (let x = variant; x; x = x.parent ? byName.get(x.parent) : null) if (x.motion && x.motion.source) return x.motion.source;
    return null;
  };
  const baseBg = (name, variant) => {
    const b = byName.get(name);
    if (!b || !b.states.panel) fail(variant, `base ${name} has no panel record`);
    return b.states.panel['bg-color'];
  };

  for (const variant of sys.variants) {
    if (variant.abstract) continue;
    const cls = `.tv-${variant.variation}`;
    const isButton = variant.class === 'Button' || variant.class === 'OptionButton';
    const isLineEdit = variant.class === 'LineEdit';
    const isBar = variant.class === 'ProgressBar';
    const boxes = new Set(variant.styleboxes || []);
    out.push(`/* ${variant.variation}: ${variant.class}${variant.parent ? ` → ${variant.parent}` : ''} · ${variant.prefix} · ${variant.context} */`);

    if (isBar) {
      const base = new Map([['position', 'relative']]);
      if (boxes.has('background')) {
        for (const [p, x] of boxDecls(variant, variant.states.background)) if (!(p.startsWith('margin-') && x === '0')) base.set(p, x);
      } else {
        base.set('height', '100%');
      }
      rule(cls, base);
      if (boxes.has('fill')) {
        const fill = new Map([['position', 'absolute'], ['top', '0'], ['left', '0'], ['display', 'block']]);
        for (const [p, x] of boxDecls(variant, variant.states.fill)) {
          if (p === 'position' || (p.startsWith('margin-') && x === '0')) continue;
          fill.set(p, x);
        }
        fill.set('height', '100%');
        fill.set('width', 'calc(var(--value) * 100%)');
        rule(`${cls} > .tv-fill`, fill);
      }
      if (variant.stops && variant.stops.length) {
        for (const s of variant.stops) {
          const nn = String(s.step).padStart(2, '0');
          rule(`${cls}[data-step="${nn}"] > .tv-fill`, [`background: ${v(s.path)};`]);
        }
      }
      continue;
    }

    const mainKey = boxes.has('panel') ? 'panel' : boxes.has('normal') ? 'normal' : null;
    const mainRec = mainKey ? variant.states[mainKey] : null;
    const textRec = variant.states.normal || null;
    const base = new Map();
    if (mainRec) {
      for (const [p, x] of boxDecls(variant, mainRec)) if (!(p.startsWith('margin-') && x === '0')) base.set(p, x);
    } else if (isButton || isLineEdit) {
      base.set('position', 'relative');
    }
    if (variant.label || (textRec && textRec['font-color'])) {
      for (const [p, x] of fontDecls(variant.label, textRec && textRec['font-color'])) base.set(p, x);
    }

    // Sizes (§13.2): width/height/min-width on the base rule; wide-* on .tv-wide.
    const wide = new Map();
    for (const [name, f] of Object.entries(variant.size || {})) {
      const css = len(variant, f, `size.${name}`);
      if (name === 'width' || name === 'height' || name === 'min-width') base.set(name, css);
      else if (name === 'wide-width') wide.set('width', css);
      else if (name === 'wide-min-width') wide.set('min-width', css);
      else fail(variant, `size.${name} has no CSS form`);
    }

    // Items.
    const itemRules = new Map();
    let logo = null;
    const iconRules = new Map();
    for (const [name, f] of Object.entries(variant.items || {})) {
      if (LOGO_ITEMS.has(name)) { logo = logo || {}; logo[name] = f; continue; }
      if (NO_CSS_ITEMS.has(name)) {
        if (name === 'modulate-arrow' && f.value && f.value.value !== 1) fail(variant, 'modulate-arrow 0 has no CSS form (the arrow takes the label colour)');
        continue;
      }
      if (ICON_STATE.some(([n]) => n === name)) { iconRules.set(name, v(f.source)); continue; }
      if (name === 'h-separation') { base.set('column-gap', len(variant, f, 'h-separation')); continue; }
      if (name === 'arrow-margin') {
        // Godot draws the arrow arrow_margin from the right edge and reserves its width itself; in CSS the arrow is the
        // last flex child, so its right margin is arrow_margin minus the right content margin.
        const cmr = mainRec && mainRec['content-margin-right'];
        if (!cmr) fail(variant, 'arrow-margin needs a normal content-margin-right');
        if (!itemRules.has('tv-arrow')) itemRules.set('tv-arrow', new Map());
        itemRules.get('tv-arrow').set('margin-right', sum(variant, [[f, 'arrow-margin']], [[cmr, 'content-margin-right']]));
        continue;
      }
      const m = ITEM_MAP[name];
      if (!m) fail(variant, `item ${name} has no CSS form`);
      if (!itemRules.has(m[0])) itemRules.set(m[0], new Map());
      itemRules.get(m[0]).set(m[1], v(f.source));
    }
    if (logo) {
      const sc = textRec && textRec['font-shadow-color'];
      if (!logo['shadow-offset-x'] || !logo['shadow-offset-y'] || !sc || !sc.source) fail(variant, 'a font shadow needs both offsets and a colour');
      base.set('text-shadow', `${len(variant, logo['shadow-offset-x'], 'shadow-offset-x')} ${len(variant, logo['shadow-offset-y'], 'shadow-offset-y')} 0 ${v(sc.source)}`);
    }

    // Press and base (§13.2, §6).
    const press = isButton && variant.press ? variant.press : null;
    const pressNonZero = press && ['depth', 'hover', 'held', 'disabled'].some((k) => px(press[k]) !== 0);
    const hasPress = isButton && (pressNonZero || !!variant.base);
    const pv = (k) => (press && press[k] && press[k].source ? v(press[k].source) : '0');
    let lightBase = null;
    if (hasPress) {
      const ms = motionOf(variant);
      if (!ms) fail(variant, 'a pressable has no motion token');
      const mv = sys.cssVar(ms);
      base.set('--tv-offset', '0');
      base.set('--tv-depth', pv('depth'));
      const trans = [`transform var(${mv}-duration) var(${mv}-timing-function)`];
      if (variant.base) {
        const darkName = variant.base.dark || variant.base.any;
        base.set('--tv-base', colour(baseBg(darkName, variant)));
        if (variant.base.light) lightBase = colour(baseBg(variant.base.light, variant));
      }
      base.set('transform', 'translateY(calc(var(--tv-offset) * var(--px)))');
      if (variant.base) {
        base.set('box-shadow', '0 calc((var(--tv-depth) - var(--tv-offset)) * var(--px)) 0 var(--tv-base)');
        trans.push(`box-shadow var(${mv}-duration) var(${mv}-timing-function)`);
      }
      base.set('transition', trans.join(', '));
    } else if (variant.base && mainRec) {
      // A static surface with a base layer: the base's drawn rect below the face's (§13.2).
      const b = byName.get(variant.base.any || variant.base.dark);
      if (!b || !b.states.panel) fail(variant, 'its base has no panel record');
      const bex = b.states.panel['expand-margin-bottom'];
      const fex = mainRec['expand-margin-bottom'];
      base.set('box-shadow', `0 ${sum(variant, [[bex, 'base expand-margin-bottom']], [[fex, 'face expand-margin-bottom']])} 0 ${colour(b.states.panel['bg-color'])}`);
    }
    if (isButton) base.set('cursor', 'pointer');

    rule(cls, base);
    if (lightBase) rule(`[data-context="light"] ${cls}`, [`--tv-base: ${lightBase};`]);
    if (wide.size) rule(`${cls}.tv-wide`, wide);

    // State rules: only what differs from the base rule's drawing.
    const baseDraw = new Map();
    if (mainRec && (isButton || isLineEdit)) for (const [p, x] of boxDecls(variant, mainRec)) baseDraw.set(p, x);
    for (const [p, x] of fontDecls(null, textRec && textRec['font-color'])) baseDraw.set(p, x);
    const stateRecs = [];
    for (const [state, klass] of STATE_CLASS) {
      const rec = variant.states[state];
      const decls = new Map();
      if (rec && (isButton || isLineEdit)) {
        const draw = new Map([...boxDecls(variant, rec), ...fontDecls(null, rec['font-color'])]);
        for (const [p, x] of diff(baseDraw, draw)) decls.set(p, x);
        stateRecs.push([klass, rec]);
      }
      if (hasPress) {
        const k = { hover: 'hover', pressed: 'held', disabled: 'disabled' }[state];
        if (k && (pressNonZero || k === 'disabled')) decls.set('--tv-offset', pv(k));
        if (state === 'disabled' && variant.base) decls.set('box-shadow', 'none');
      }
      rule(`${cls}.${klass}`, decls);
    }

    // Focus (§13.2): the .tv-focus child, drawn over the state's StyleBox.
    const focus = variant.states.focus;
    if (focus && (isButton || isLineEdit)) {
      const fd = new Map([['display', 'none'], ['position', 'absolute'], ['pointer-events', 'none'], ['box-sizing', 'border-box'],
        ['border-style', 'solid']]);
      if (focus['draw-center'] && focus['draw-center'].value.value !== false && focus['bg-color'].source) fd.set('background', v(focus['bg-color'].source));
      if (!focus['border-color'].source) fail(variant, 'focus has no border colour');
      fd.set('border-color', v(focus['border-color'].source));
      for (const s of SIDES) fd.set(`border-${s}-width`, len(variant, focus[`border-width-${s}`], `focus border-width-${s}`));
      for (const c of CORNERS) fd.set(`border-${c}-radius`, len(variant, focus[`corner-radius-${c}`], `focus corner-radius-${c}`));
      const ins = focusInsets(variant, mainRec, focus);
      for (const s of SIDES) fd.set(s, ins.get(s));
      rule(`${cls} > .tv-focus`, fd);
      rule(`${cls}.is-focus > .tv-focus, ${cls}:focus-visible > .tv-focus`, ['display: block;']);
      for (const [klass, rec] of stateRecs) {
        const si = focusInsets(variant, rec, focus);
        const d = new Map();
        for (const s of SIDES) if (si.get(s) !== ins.get(s)) d.set(s, si.get(s));
        rule(`${cls}.${klass} > .tv-focus`, d);
      }
      const fc = fontDecls(null, focus['font-color']);
      const fcd = diff(new Map(fontDecls(null, textRec && textRec['font-color'])), fc);
      rule(`${cls}.is-focus, ${cls}:focus-visible`, fcd);
    }

    for (const [child, decls] of itemRules) rule(`${cls} .${child}`, decls);
    for (const [name, klass] of ICON_STATE) {
      if (!iconRules.has(name)) continue;
      const sel = !klass ? `${cls} .tv-icon` : klass === 'is-focus' ? `${cls}.is-focus .tv-icon, ${cls}:focus-visible .tv-icon` : `${cls}.${klass} .tv-icon`;
      rule(sel, [`color: ${iconRules.get(name)};`]);
    }
  }
  return out.join('\n') + '\n';
}

module.exports = { emitComponentsCss, HEADER };
